/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.api;

import com.cobo.waas2.ApiClient;
import com.cobo.waas2.ApiException;
import com.cobo.waas2.Configuration;
import com.cobo.waas2.model.ErrorResponse;
import com.cobo.waas2.model.EstimatedFixedFee;
import com.cobo.waas2.model.FeeStationCheckFeeStationUsage;
import com.cobo.waas2.model.FeeStationCheckFeeStationUsageResponse;
import com.cobo.waas2.model.FeeStationTransfer;
import com.cobo.waas2.model.ListAddresses200Response;
import com.cobo.waas2.model.ListTokenBalancesForFeeStation200Response;
import com.cobo.waas2.model.ListTransactions200Response;
import com.cobo.waas2.model.TransactionDetail;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FeeStationApi
 */
@Disabled
public class FeeStationApiTest {
    ApiClient defaultClient = Configuration.getDefaultApiClient();
    // set custom base url
    {
        defaultClient.setBasePath("https://api.sandbox.cobo.com/v2");
        defaultClient.setPrivKey("<YOUR_API_PRIVATE_KEY_IN_HEX>");
    }
    private final FeeStationApi api = new FeeStationApi();

    /**
     * Check Fee Station usage
     *
     * This operation evaluates Fee Station usage for the current transaction.   It determines whether Fee station can be used, checks if the Fee Station balance is sufficient, and returns a breakdown of the amounts involved, including any portion that must be covered by the user or sponsored in USDT (U). 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkFeeStationUsageTest() throws ApiException {
        FeeStationCheckFeeStationUsage feeStationCheckFeeStationUsage = null;
        FeeStationCheckFeeStationUsageResponse response = api.checkFeeStationUsage(feeStationCheckFeeStationUsage);
        // TODO: test validations
    }

    /**
     * Estimate fee for Fee Station transaction
     *
     * This operation estimates the gas fee required for a top-up transaction sent by [Fee Station](https://manuals.cobo.com/en/portal/fee-station/introduction) to provide gas to the sender of the original transaction.  You need to provide the token ID and transfer amount.  For more information about transaction fee models and how fees are calculated, refer to [Estimate transaction fee](https://www.cobo.com/developers/v2/guides/transactions/estimate-fees). 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void estimateFeeStationFeeTest() throws ApiException {
        FeeStationTransfer feeStationTransfer = null;
        EstimatedFixedFee response = api.estimateFeeStationFee(feeStationTransfer);
        // TODO: test validations
    }

    /**
     * Get Fee Station transaction information
     *
     * This operation retrieves detailed information about a specified Fee Station transaction record, such as the transaction status, source address, destination address, and timestamp. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFeeStationTransactionByIdTest() throws ApiException {
        UUID transactionId = null;
        TransactionDetail response = api.getFeeStationTransactionById(transactionId);
        // TODO: test validations
    }

    /**
     * List Fee Station addresses
     *
     * This operation retrieves a list of deposit addresses of your Fee Station, including the chain ID, address, and additional information. You can filter the result by chain ID and address. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listFeeStationAddressesTest() throws ApiException {
        String chainIds = null;
        String addresses = null;
        Integer limit = null;
        String before = null;
        String after = null;
        ListAddresses200Response response = api.listFeeStationAddresses(chainIds, addresses, limit, before, after);
        // TODO: test validations
    }

    /**
     * List all Fee Station transactions
     *
     * This operation retrieves all Fee Station transactions under your organization.  You can filter the results by request ID, Cobo ID, transaction ID, transaction hash, type, status, and timestamp. You can also paginate and sort your query results. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listFeeStationTransactionsTest() throws ApiException {
        String requestId = null;
        String coboIds = null;
        String transactionIds = null;
        String transactionHashes = null;
        String types = null;
        String statuses = null;
        String chainIds = null;
        String tokenIds = null;
        String assetIds = null;
        Long minCreatedTimestamp = null;
        Long maxCreatedTimestamp = null;
        Integer limit = null;
        String before = null;
        String after = null;
        String direction = null;
        ListTransactions200Response response = api.listFeeStationTransactions(requestId, coboIds, transactionIds, transactionHashes, types, statuses, chainIds, tokenIds, assetIds, minCreatedTimestamp, maxCreatedTimestamp, limit, before, after, direction);
        // TODO: test validations
    }

    /**
     * List Fee Station token balances
     *
     * The operation retrieves a list of token balances within your Fee Station. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTokenBalancesForFeeStationTest() throws ApiException {
        String tokenIds = null;
        Integer limit = null;
        String before = null;
        String after = null;
        ListTokenBalancesForFeeStation200Response response = api.listTokenBalancesForFeeStation(tokenIds, limit, before, after);
        // TODO: test validations
    }

}
