/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.api;

import com.cobo.waas2.ApiCallback;
import com.cobo.waas2.ApiClient;
import com.cobo.waas2.ApiException;
import com.cobo.waas2.ApiResponse;
import com.cobo.waas2.Configuration;
import com.cobo.waas2.Pair;
import com.cobo.waas2.ProgressRequestBody;
import com.cobo.waas2.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.cobo.waas2.model.ErrorResponse;
import com.cobo.waas2.model.GraphQLRequest;
import com.cobo.waas2.model.GraphQLResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GraphQlApi {
    private ApiClient localVarApiClient;

    public GraphQlApi() {
        this(Configuration.getDefaultApiClient());
    }

    public GraphQlApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for executeGraphql
     * @param graphQLRequest The request body to generate addresses within a specified wallet. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A staking activity has been successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td> Bad request. Your request contains malformed syntax or invalid parameters. </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td> Internal server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call executeGraphqlCall(GraphQLRequest graphQLRequest, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = graphQLRequest;

        // create path and map variables
        String localVarPath = "/graphql";

        List<Pair> localVarQueryParams = new ArrayList<>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<>();
        Map<String, String> localVarHeaderParams = new HashMap<>();
        Map<String, String> localVarCookieParams = new HashMap<>();
        Map<String, Object> localVarFormParams = new HashMap<>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {};
        return localVarApiClient.buildCall(null, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call executeGraphqlValidateBeforeCall(GraphQLRequest graphQLRequest, final ApiCallback _callback) throws ApiException {
        return executeGraphqlCall(graphQLRequest, _callback);

    }

    /**
     * Execute a GraphQL query or mutation
     * This endpoint executes a GraphQL query or mutation. The request body must include a valid GraphQL query string. 
     * @param graphQLRequest The request body to generate addresses within a specified wallet. (optional)
     * @return GraphQLResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A staking activity has been successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td> Bad request. Your request contains malformed syntax or invalid parameters. </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td> Internal server error. </td><td>  -  </td></tr>
     </table>
     */
    public GraphQLResponse executeGraphql(GraphQLRequest graphQLRequest) throws ApiException {
        ApiResponse<GraphQLResponse> localVarResp = executeGraphqlWithHttpInfo(graphQLRequest);
        return localVarResp.getData();
    }

    /**
     * Execute a GraphQL query or mutation
     * This endpoint executes a GraphQL query or mutation. The request body must include a valid GraphQL query string. 
     * @param graphQLRequest The request body to generate addresses within a specified wallet. (optional)
     * @return ApiResponse&lt;GraphQLResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A staking activity has been successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td> Bad request. Your request contains malformed syntax or invalid parameters. </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td> Internal server error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GraphQLResponse> executeGraphqlWithHttpInfo(GraphQLRequest graphQLRequest) throws ApiException {
        okhttp3.Call localVarCall = executeGraphqlValidateBeforeCall(graphQLRequest, null);
        Type localVarReturnType = new TypeToken<GraphQLResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Execute a GraphQL query or mutation (asynchronously)
     * This endpoint executes a GraphQL query or mutation. The request body must include a valid GraphQL query string. 
     * @param graphQLRequest The request body to generate addresses within a specified wallet. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A staking activity has been successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td> Bad request. Your request contains malformed syntax or invalid parameters. </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td> Internal server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call executeGraphqlAsync(GraphQLRequest graphQLRequest, final ApiCallback<GraphQLResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = executeGraphqlValidateBeforeCall(graphQLRequest, _callback);
        Type localVarReturnType = new TypeToken<GraphQLResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
