/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.cobo.waas2.model.PaymentSourceType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * AllocationRecord
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class AllocationRecord {
  public static final String SERIALIZED_NAME_ALLOCATION_RECORD_ID = "allocation_record_id";
  @SerializedName(SERIALIZED_NAME_ALLOCATION_RECORD_ID)
  private String allocationRecordId;

  public static final String SERIALIZED_NAME_BATCH_ALLOCATION_ID = "batch_allocation_id";
  @SerializedName(SERIALIZED_NAME_BATCH_ALLOCATION_ID)
  private String batchAllocationId;

  public static final String SERIALIZED_NAME_TOKEN_ID = "token_id";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  private String tokenId;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private String amount;

  public static final String SERIALIZED_NAME_SOURCE_TYPE = "source_type";
  @SerializedName(SERIALIZED_NAME_SOURCE_TYPE)
  private PaymentSourceType sourceType;

  public static final String SERIALIZED_NAME_FROM_MERCHANT_ID = "from_merchant_id";
  @SerializedName(SERIALIZED_NAME_FROM_MERCHANT_ID)
  private String fromMerchantId;

  public static final String SERIALIZED_NAME_TO_MERCHANT_ID = "to_merchant_id";
  @SerializedName(SERIALIZED_NAME_TO_MERCHANT_ID)
  private String toMerchantId;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public AllocationRecord() {
  }

  public AllocationRecord allocationRecordId(String allocationRecordId) {
    this.allocationRecordId = allocationRecordId;
    return this;
  }

   /**
   * The allocation record ID generated by Cobo.
   * @return allocationRecordId
  **/
  @javax.annotation.Nonnull
  public String getAllocationRecordId() {
    return allocationRecordId;
  }

  public void setAllocationRecordId(String allocationRecordId) {
    this.allocationRecordId = allocationRecordId;
  }


  public AllocationRecord batchAllocationId(String batchAllocationId) {
    this.batchAllocationId = batchAllocationId;
    return this;
  }

   /**
   * The batch allocation ID generated by Cobo.
   * @return batchAllocationId
  **/
  @javax.annotation.Nonnull
  public String getBatchAllocationId() {
    return batchAllocationId;
  }

  public void setBatchAllocationId(String batchAllocationId) {
    this.batchAllocationId = batchAllocationId;
  }


  public AllocationRecord tokenId(String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

   /**
   * The ID of the cryptocurrency you want to allocation. Supported values:  - USDC: &#x60;ETH_USDC&#x60;, &#x60;ARBITRUM_USDC&#x60;, &#x60;SOL_USDC&#x60;, &#x60;BASE_USDC&#x60;, &#x60;MATIC_USDC&#x60;, &#x60;BSC_USDC&#x60; - USDT: &#x60;TRON_USDT&#x60;, &#x60;ETH_USDT&#x60;, &#x60;ARBITRUM_USDT&#x60;, &#x60;SOL_USDT&#x60;, &#x60;BASE_USDT&#x60;, &#x60;MATIC_USDT&#x60;, &#x60;BSC_USDT&#x60; 
   * @return tokenId
  **/
  @javax.annotation.Nonnull
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  public AllocationRecord amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The allocation amount. 
   * @return amount
  **/
  @javax.annotation.Nonnull
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }


  public AllocationRecord sourceType(PaymentSourceType sourceType) {
    this.sourceType = sourceType;
    return this;
  }

   /**
   * Get sourceType
   * @return sourceType
  **/
  @javax.annotation.Nonnull
  public PaymentSourceType getSourceType() {
    return sourceType;
  }

  public void setSourceType(PaymentSourceType sourceType) {
    this.sourceType = sourceType;
  }


  public AllocationRecord fromMerchantId(String fromMerchantId) {
    this.fromMerchantId = fromMerchantId;
    return this;
  }

   /**
   * Only used in Merchant allocation type. The merchant ID. 
   * @return fromMerchantId
  **/
  @javax.annotation.Nullable
  public String getFromMerchantId() {
    return fromMerchantId;
  }

  public void setFromMerchantId(String fromMerchantId) {
    this.fromMerchantId = fromMerchantId;
  }


  public AllocationRecord toMerchantId(String toMerchantId) {
    this.toMerchantId = toMerchantId;
    return this;
  }

   /**
   * Only used in Merchant allocation type. The merchant ID. 
   * @return toMerchantId
  **/
  @javax.annotation.Nullable
  public String getToMerchantId() {
    return toMerchantId;
  }

  public void setToMerchantId(String toMerchantId) {
    this.toMerchantId = toMerchantId;
  }


  public AllocationRecord description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AllocationRecord instance itself
   */
  public AllocationRecord putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllocationRecord allocationRecord = (AllocationRecord) o;
    return Objects.equals(this.allocationRecordId, allocationRecord.allocationRecordId) &&
        Objects.equals(this.batchAllocationId, allocationRecord.batchAllocationId) &&
        Objects.equals(this.tokenId, allocationRecord.tokenId) &&
        Objects.equals(this.amount, allocationRecord.amount) &&
        Objects.equals(this.sourceType, allocationRecord.sourceType) &&
        Objects.equals(this.fromMerchantId, allocationRecord.fromMerchantId) &&
        Objects.equals(this.toMerchantId, allocationRecord.toMerchantId) &&
        Objects.equals(this.description, allocationRecord.description)&&
        Objects.equals(this.additionalProperties, allocationRecord.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allocationRecordId, batchAllocationId, tokenId, amount, sourceType, fromMerchantId, toMerchantId, description, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllocationRecord {\n");
    sb.append("    allocationRecordId: ").append(toIndentedString(allocationRecordId)).append("\n");
    sb.append("    batchAllocationId: ").append(toIndentedString(batchAllocationId)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    fromMerchantId: ").append(toIndentedString(fromMerchantId)).append("\n");
    sb.append("    toMerchantId: ").append(toIndentedString(toMerchantId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("allocation_record_id");
    openapiFields.add("batch_allocation_id");
    openapiFields.add("token_id");
    openapiFields.add("amount");
    openapiFields.add("source_type");
    openapiFields.add("from_merchant_id");
    openapiFields.add("to_merchant_id");
    openapiFields.add("description");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("allocation_record_id");
    openapiRequiredFields.add("batch_allocation_id");
    openapiRequiredFields.add("token_id");
    openapiRequiredFields.add("amount");
    openapiRequiredFields.add("source_type");
    openapiRequiredFields.add("description");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AllocationRecord
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AllocationRecord.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AllocationRecord is not found in the empty JSON string", AllocationRecord.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AllocationRecord.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("allocation_record_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `allocation_record_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("allocation_record_id").toString()));
      }
      if (!jsonObj.get("batch_allocation_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `batch_allocation_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("batch_allocation_id").toString()));
      }
      if (!jsonObj.get("token_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_id").toString()));
      }
      if (!jsonObj.get("amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount").toString()));
      }
      // validate the required field `source_type`
      PaymentSourceType.validateJsonElement(jsonObj.get("source_type"));
      if ((jsonObj.get("from_merchant_id") != null && !jsonObj.get("from_merchant_id").isJsonNull()) && !jsonObj.get("from_merchant_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `from_merchant_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from_merchant_id").toString()));
      }
      if ((jsonObj.get("to_merchant_id") != null && !jsonObj.get("to_merchant_id").isJsonNull()) && !jsonObj.get("to_merchant_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `to_merchant_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("to_merchant_id").toString()));
      }
      if (!jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AllocationRecord.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AllocationRecord' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AllocationRecord> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AllocationRecord.class));

       return (TypeAdapter<T>) new TypeAdapter<AllocationRecord>() {
           @Override
           public void write(JsonWriter out, AllocationRecord value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AllocationRecord read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AllocationRecord instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AllocationRecord given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AllocationRecord
  * @throws IOException if the JSON string is invalid with respect to AllocationRecord
  */
  public static AllocationRecord fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AllocationRecord.class);
  }

 /**
  * Convert an instance of AllocationRecord to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

