/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.cobo.waas2.model.BankProvider;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * BankSignatureInfoSgb
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class BankSignatureInfoSgb {
  public static final String SERIALIZED_NAME_BANK_PROVIDER = "bank_provider";
  @SerializedName(SERIALIZED_NAME_BANK_PROVIDER)
  private BankProvider bankProvider;

  public static final String SERIALIZED_NAME_METHOD = "method";
  @SerializedName(SERIALIZED_NAME_METHOD)
  private String method;

  public static final String SERIALIZED_NAME_URL_PATH = "url_path";
  @SerializedName(SERIALIZED_NAME_URL_PATH)
  private String urlPath;

  public static final String SERIALIZED_NAME_QUERY_STRING = "query_string";
  @SerializedName(SERIALIZED_NAME_QUERY_STRING)
  private Object queryString;

  public static final String SERIALIZED_NAME_BODY_STRING = "body_string";
  @SerializedName(SERIALIZED_NAME_BODY_STRING)
  private String bodyString;

  public static final String SERIALIZED_NAME_ORG_ID = "org_id";
  @SerializedName(SERIALIZED_NAME_ORG_ID)
  private String orgId;

  public static final String SERIALIZED_NAME_ORG_NAME = "org_name";
  @SerializedName(SERIALIZED_NAME_ORG_NAME)
  private String orgName;

  public static final String SERIALIZED_NAME_CRYPTO_AMOUNT = "crypto_amount";
  @SerializedName(SERIALIZED_NAME_CRYPTO_AMOUNT)
  private String cryptoAmount;

  public BankSignatureInfoSgb() {
  }

  public BankSignatureInfoSgb bankProvider(BankProvider bankProvider) {
    this.bankProvider = bankProvider;
    return this;
  }

   /**
   * Get bankProvider
   * @return bankProvider
  **/
  @javax.annotation.Nonnull
  public BankProvider getBankProvider() {
    return bankProvider;
  }

  public void setBankProvider(BankProvider bankProvider) {
    this.bankProvider = bankProvider;
  }


  public BankSignatureInfoSgb method(String method) {
    this.method = method;
    return this;
  }

   /**
   * The HTTP method of the API request.
   * @return method
  **/
  @javax.annotation.Nonnull
  public String getMethod() {
    return method;
  }

  public void setMethod(String method) {
    this.method = method;
  }


  public BankSignatureInfoSgb urlPath(String urlPath) {
    this.urlPath = urlPath;
    return this;
  }

   /**
   * The URL path of the API request.
   * @return urlPath
  **/
  @javax.annotation.Nonnull
  public String getUrlPath() {
    return urlPath;
  }

  public void setUrlPath(String urlPath) {
    this.urlPath = urlPath;
  }


  public BankSignatureInfoSgb queryString(Object queryString) {
    this.queryString = queryString;
    return this;
  }

   /**
   * The query parameters of the API request.
   * @return queryString
  **/
  @javax.annotation.Nullable
  public Object getQueryString() {
    return queryString;
  }

  public void setQueryString(Object queryString) {
    this.queryString = queryString;
  }


  public BankSignatureInfoSgb bodyString(String bodyString) {
    this.bodyString = bodyString;
    return this;
  }

   /**
   * The body of the API request.
   * @return bodyString
  **/
  @javax.annotation.Nullable
  public String getBodyString() {
    return bodyString;
  }

  public void setBodyString(String bodyString) {
    this.bodyString = bodyString;
  }


  public BankSignatureInfoSgb orgId(String orgId) {
    this.orgId = orgId;
    return this;
  }

   /**
   * The ID of the organization.
   * @return orgId
  **/
  @javax.annotation.Nonnull
  public String getOrgId() {
    return orgId;
  }

  public void setOrgId(String orgId) {
    this.orgId = orgId;
  }


  public BankSignatureInfoSgb orgName(String orgName) {
    this.orgName = orgName;
    return this;
  }

   /**
   * The name of the organization.
   * @return orgName
  **/
  @javax.annotation.Nonnull
  public String getOrgName() {
    return orgName;
  }

  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }


  public BankSignatureInfoSgb cryptoAmount(String cryptoAmount) {
    this.cryptoAmount = cryptoAmount;
    return this;
  }

   /**
   * The amount of the cryptocurrency.
   * @return cryptoAmount
  **/
  @javax.annotation.Nonnull
  public String getCryptoAmount() {
    return cryptoAmount;
  }

  public void setCryptoAmount(String cryptoAmount) {
    this.cryptoAmount = cryptoAmount;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the BankSignatureInfoSgb instance itself
   */
  public BankSignatureInfoSgb putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankSignatureInfoSgb bankSignatureInfoSgb = (BankSignatureInfoSgb) o;
    return Objects.equals(this.bankProvider, bankSignatureInfoSgb.bankProvider) &&
        Objects.equals(this.method, bankSignatureInfoSgb.method) &&
        Objects.equals(this.urlPath, bankSignatureInfoSgb.urlPath) &&
        Objects.equals(this.queryString, bankSignatureInfoSgb.queryString) &&
        Objects.equals(this.bodyString, bankSignatureInfoSgb.bodyString) &&
        Objects.equals(this.orgId, bankSignatureInfoSgb.orgId) &&
        Objects.equals(this.orgName, bankSignatureInfoSgb.orgName) &&
        Objects.equals(this.cryptoAmount, bankSignatureInfoSgb.cryptoAmount)&&
        Objects.equals(this.additionalProperties, bankSignatureInfoSgb.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankProvider, method, urlPath, queryString, bodyString, orgId, orgName, cryptoAmount, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankSignatureInfoSgb {\n");
    sb.append("    bankProvider: ").append(toIndentedString(bankProvider)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    urlPath: ").append(toIndentedString(urlPath)).append("\n");
    sb.append("    queryString: ").append(toIndentedString(queryString)).append("\n");
    sb.append("    bodyString: ").append(toIndentedString(bodyString)).append("\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    orgName: ").append(toIndentedString(orgName)).append("\n");
    sb.append("    cryptoAmount: ").append(toIndentedString(cryptoAmount)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bank_provider");
    openapiFields.add("method");
    openapiFields.add("url_path");
    openapiFields.add("query_string");
    openapiFields.add("body_string");
    openapiFields.add("org_id");
    openapiFields.add("org_name");
    openapiFields.add("crypto_amount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("bank_provider");
    openapiRequiredFields.add("method");
    openapiRequiredFields.add("url_path");
    openapiRequiredFields.add("org_id");
    openapiRequiredFields.add("org_name");
    openapiRequiredFields.add("crypto_amount");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BankSignatureInfoSgb
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BankSignatureInfoSgb.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BankSignatureInfoSgb is not found in the empty JSON string", BankSignatureInfoSgb.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BankSignatureInfoSgb.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `bank_provider`
      BankProvider.validateJsonElement(jsonObj.get("bank_provider"));
      if (!jsonObj.get("method").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `method` to be a primitive type in the JSON string but got `%s`", jsonObj.get("method").toString()));
      }
      if (!jsonObj.get("url_path").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url_path` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url_path").toString()));
      }
      if ((jsonObj.get("body_string") != null && !jsonObj.get("body_string").isJsonNull()) && !jsonObj.get("body_string").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `body_string` to be a primitive type in the JSON string but got `%s`", jsonObj.get("body_string").toString()));
      }
      if (!jsonObj.get("org_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `org_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("org_id").toString()));
      }
      if (!jsonObj.get("org_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `org_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("org_name").toString()));
      }
      if (!jsonObj.get("crypto_amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `crypto_amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("crypto_amount").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BankSignatureInfoSgb.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BankSignatureInfoSgb' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BankSignatureInfoSgb> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BankSignatureInfoSgb.class));

       return (TypeAdapter<T>) new TypeAdapter<BankSignatureInfoSgb>() {
           @Override
           public void write(JsonWriter out, BankSignatureInfoSgb value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public BankSignatureInfoSgb read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             BankSignatureInfoSgb instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BankSignatureInfoSgb given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BankSignatureInfoSgb
  * @throws IOException if the JSON string is invalid with respect to BankSignatureInfoSgb
  */
  public static BankSignatureInfoSgb fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BankSignatureInfoSgb.class);
  }

 /**
  * Convert an instance of BankSignatureInfoSgb to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

