/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.cobo.waas2.model.FeeStationFiatTransactionType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * The information about a fiat transaction.
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class FeeStationFiatTransaction {
  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transaction_id";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  private String transactionId;

  public static final String SERIALIZED_NAME_MAIN_TRANSACTION_ID = "main_transaction_id";
  @SerializedName(SERIALIZED_NAME_MAIN_TRANSACTION_ID)
  private UUID mainTransactionId;

  public static final String SERIALIZED_NAME_TRANSACTION_TYPE = "transaction_type";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_TYPE)
  private FeeStationFiatTransactionType transactionType;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private String amount;

  public static final String SERIALIZED_NAME_FIAT_CURRENCY = "fiat_currency";
  @SerializedName(SERIALIZED_NAME_FIAT_CURRENCY)
  private String fiatCurrency;

  /**
   * The status of the fiat transaction. Possible values include:   - &#x60;Created&#x60;: The transaction has been created.   - &#x60;Succeeded&#x60;: The transaction has been completed successfully. 
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    CREATED("Created"),
    
    SUCCEEDED("Succeeded");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  public static final String SERIALIZED_NAME_COBO_CATEGORY = "cobo_category";
  @SerializedName(SERIALIZED_NAME_COBO_CATEGORY)
  private List<String> coboCategory = new ArrayList<>();

  public static final String SERIALIZED_NAME_CREATED_TIMESTAMP = "created_timestamp";
  @SerializedName(SERIALIZED_NAME_CREATED_TIMESTAMP)
  private Long createdTimestamp;

  public static final String SERIALIZED_NAME_MODIFIED_TIMESTAMP = "modified_timestamp";
  @SerializedName(SERIALIZED_NAME_MODIFIED_TIMESTAMP)
  private Long modifiedTimestamp;

  public FeeStationFiatTransaction() {
  }

  public FeeStationFiatTransaction transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * The transaction ID.
   * @return transactionId
  **/
  @javax.annotation.Nonnull
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  public FeeStationFiatTransaction mainTransactionId(UUID mainTransactionId) {
    this.mainTransactionId = mainTransactionId;
    return this;
  }

   /**
   * The UUID of the parent (main) transaction that this record is associated with. Set only when the current record is a gas/fee transaction initiated by FeeStation; omit for main transactions.
   * @return mainTransactionId
  **/
  @javax.annotation.Nullable
  public UUID getMainTransactionId() {
    return mainTransactionId;
  }

  public void setMainTransactionId(UUID mainTransactionId) {
    this.mainTransactionId = mainTransactionId;
  }


  public FeeStationFiatTransaction transactionType(FeeStationFiatTransactionType transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Get transactionType
   * @return transactionType
  **/
  @javax.annotation.Nonnull
  public FeeStationFiatTransactionType getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(FeeStationFiatTransactionType transactionType) {
    this.transactionType = transactionType;
  }


  public FeeStationFiatTransaction amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The transaction amount.
   * @return amount
  **/
  @javax.annotation.Nonnull
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }


  public FeeStationFiatTransaction fiatCurrency(String fiatCurrency) {
    this.fiatCurrency = fiatCurrency;
    return this;
  }

   /**
   * The fiat currency of the transaction. Possible values include:   - &#x60;USD&#x60;: US Dollar. 
   * @return fiatCurrency
  **/
  @javax.annotation.Nonnull
  public String getFiatCurrency() {
    return fiatCurrency;
  }

  public void setFiatCurrency(String fiatCurrency) {
    this.fiatCurrency = fiatCurrency;
  }


  public FeeStationFiatTransaction status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the fiat transaction. Possible values include:   - &#x60;Created&#x60;: The transaction has been created.   - &#x60;Succeeded&#x60;: The transaction has been completed successfully. 
   * @return status
  **/
  @javax.annotation.Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public FeeStationFiatTransaction coboCategory(List<String> coboCategory) {
    this.coboCategory = coboCategory;
    return this;
  }

  public FeeStationFiatTransaction addCoboCategoryItem(String coboCategoryItem) {
    if (this.coboCategory == null) {
      this.coboCategory = new ArrayList<>();
    }
    this.coboCategory.add(coboCategoryItem);
    return this;
  }

   /**
   * The Cobo category of the transaction.
   * @return coboCategory
  **/
  @javax.annotation.Nullable
  public List<String> getCoboCategory() {
    return coboCategory;
  }

  public void setCoboCategory(List<String> coboCategory) {
    this.coboCategory = coboCategory;
  }


  public FeeStationFiatTransaction createdTimestamp(Long createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
    return this;
  }

   /**
   * The time when the transaction was created, in Unix timestamp format, measured in milliseconds.
   * @return createdTimestamp
  **/
  @javax.annotation.Nullable
  public Long getCreatedTimestamp() {
    return createdTimestamp;
  }

  public void setCreatedTimestamp(Long createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }


  public FeeStationFiatTransaction modifiedTimestamp(Long modifiedTimestamp) {
    this.modifiedTimestamp = modifiedTimestamp;
    return this;
  }

   /**
   * The time when the transaction was last modified, in Unix timestamp format, measured in milliseconds.
   * @return modifiedTimestamp
  **/
  @javax.annotation.Nullable
  public Long getModifiedTimestamp() {
    return modifiedTimestamp;
  }

  public void setModifiedTimestamp(Long modifiedTimestamp) {
    this.modifiedTimestamp = modifiedTimestamp;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the FeeStationFiatTransaction instance itself
   */
  public FeeStationFiatTransaction putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeeStationFiatTransaction feeStationFiatTransaction = (FeeStationFiatTransaction) o;
    return Objects.equals(this.transactionId, feeStationFiatTransaction.transactionId) &&
        Objects.equals(this.mainTransactionId, feeStationFiatTransaction.mainTransactionId) &&
        Objects.equals(this.transactionType, feeStationFiatTransaction.transactionType) &&
        Objects.equals(this.amount, feeStationFiatTransaction.amount) &&
        Objects.equals(this.fiatCurrency, feeStationFiatTransaction.fiatCurrency) &&
        Objects.equals(this.status, feeStationFiatTransaction.status) &&
        Objects.equals(this.coboCategory, feeStationFiatTransaction.coboCategory) &&
        Objects.equals(this.createdTimestamp, feeStationFiatTransaction.createdTimestamp) &&
        Objects.equals(this.modifiedTimestamp, feeStationFiatTransaction.modifiedTimestamp)&&
        Objects.equals(this.additionalProperties, feeStationFiatTransaction.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, mainTransactionId, transactionType, amount, fiatCurrency, status, coboCategory, createdTimestamp, modifiedTimestamp, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeeStationFiatTransaction {\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    mainTransactionId: ").append(toIndentedString(mainTransactionId)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    fiatCurrency: ").append(toIndentedString(fiatCurrency)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    coboCategory: ").append(toIndentedString(coboCategory)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    modifiedTimestamp: ").append(toIndentedString(modifiedTimestamp)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("transaction_id");
    openapiFields.add("main_transaction_id");
    openapiFields.add("transaction_type");
    openapiFields.add("amount");
    openapiFields.add("fiat_currency");
    openapiFields.add("status");
    openapiFields.add("cobo_category");
    openapiFields.add("created_timestamp");
    openapiFields.add("modified_timestamp");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("transaction_id");
    openapiRequiredFields.add("transaction_type");
    openapiRequiredFields.add("amount");
    openapiRequiredFields.add("fiat_currency");
    openapiRequiredFields.add("status");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to FeeStationFiatTransaction
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FeeStationFiatTransaction.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FeeStationFiatTransaction is not found in the empty JSON string", FeeStationFiatTransaction.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FeeStationFiatTransaction.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("transaction_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transaction_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transaction_id").toString()));
      }
      if ((jsonObj.get("main_transaction_id") != null && !jsonObj.get("main_transaction_id").isJsonNull()) && !jsonObj.get("main_transaction_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `main_transaction_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("main_transaction_id").toString()));
      }
      // validate the required field `transaction_type`
      FeeStationFiatTransactionType.validateJsonElement(jsonObj.get("transaction_type"));
      if (!jsonObj.get("amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount").toString()));
      }
      if (!jsonObj.get("fiat_currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fiat_currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fiat_currency").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the required field `status`
      StatusEnum.validateJsonElement(jsonObj.get("status"));
      // ensure the optional json data is an array if present
      if (jsonObj.get("cobo_category") != null && !jsonObj.get("cobo_category").isJsonNull() && !jsonObj.get("cobo_category").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `cobo_category` to be an array in the JSON string but got `%s`", jsonObj.get("cobo_category").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FeeStationFiatTransaction.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FeeStationFiatTransaction' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FeeStationFiatTransaction> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FeeStationFiatTransaction.class));

       return (TypeAdapter<T>) new TypeAdapter<FeeStationFiatTransaction>() {
           @Override
           public void write(JsonWriter out, FeeStationFiatTransaction value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public FeeStationFiatTransaction read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             FeeStationFiatTransaction instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FeeStationFiatTransaction given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FeeStationFiatTransaction
  * @throws IOException if the JSON string is invalid with respect to FeeStationFiatTransaction
  */
  public static FeeStationFiatTransaction fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FeeStationFiatTransaction.class);
  }

 /**
  * Convert an instance of FeeStationFiatTransaction to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

