/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.cobo.waas2.model.BridgingFee;
import com.cobo.waas2.model.CommissionFee;
import com.cobo.waas2.model.PaymentPayoutStatus;
import com.cobo.waas2.model.PaymentTransaction;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * PaymentPayoutItemDetail
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class PaymentPayoutItemDetail {
  public static final String SERIALIZED_NAME_PAYOUT_ITEM_ID = "payout_item_id";
  @SerializedName(SERIALIZED_NAME_PAYOUT_ITEM_ID)
  private String payoutItemId;

  public static final String SERIALIZED_NAME_PAYOUT_ID = "payout_id";
  @SerializedName(SERIALIZED_NAME_PAYOUT_ID)
  private String payoutId;

  public static final String SERIALIZED_NAME_TOKEN_ID = "token_id";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  private String tokenId;

  public static final String SERIALIZED_NAME_CHAIN_ID = "chain_id";
  @SerializedName(SERIALIZED_NAME_CHAIN_ID)
  private String chainId;

  public static final String SERIALIZED_NAME_MERCHANT_ID = "merchant_id";
  @SerializedName(SERIALIZED_NAME_MERCHANT_ID)
  private String merchantId;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private String amount;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private PaymentPayoutStatus status;

  public static final String SERIALIZED_NAME_TRANSACTIONS = "transactions";
  @SerializedName(SERIALIZED_NAME_TRANSACTIONS)
  private List<PaymentTransaction> transactions = new ArrayList<>();

  public static final String SERIALIZED_NAME_CREATED_TIMESTAMP = "created_timestamp";
  @SerializedName(SERIALIZED_NAME_CREATED_TIMESTAMP)
  private Integer createdTimestamp;

  public static final String SERIALIZED_NAME_UPDATED_TIMESTAMP = "updated_timestamp";
  @SerializedName(SERIALIZED_NAME_UPDATED_TIMESTAMP)
  private Integer updatedTimestamp;

  public static final String SERIALIZED_NAME_CRYPTO_ADDRESS_ID = "crypto_address_id";
  @SerializedName(SERIALIZED_NAME_CRYPTO_ADDRESS_ID)
  private String cryptoAddressId;

  public static final String SERIALIZED_NAME_CRYPTO_ADDRESS = "crypto_address";
  @SerializedName(SERIALIZED_NAME_CRYPTO_ADDRESS)
  private String cryptoAddress;

  public static final String SERIALIZED_NAME_COMMISSION_FEE = "commission_fee";
  @SerializedName(SERIALIZED_NAME_COMMISSION_FEE)
  private CommissionFee commissionFee;

  public static final String SERIALIZED_NAME_BRIDGING_FEE = "bridging_fee";
  @SerializedName(SERIALIZED_NAME_BRIDGING_FEE)
  private BridgingFee bridgingFee;

  public PaymentPayoutItemDetail() {
  }

  public PaymentPayoutItemDetail payoutItemId(String payoutItemId) {
    this.payoutItemId = payoutItemId;
    return this;
  }

   /**
   * The payout item ID generated by Cobo.
   * @return payoutItemId
  **/
  @javax.annotation.Nonnull
  public String getPayoutItemId() {
    return payoutItemId;
  }

  public void setPayoutItemId(String payoutItemId) {
    this.payoutItemId = payoutItemId;
  }


  public PaymentPayoutItemDetail payoutId(String payoutId) {
    this.payoutId = payoutId;
    return this;
  }

   /**
   * The payout ID generated by Cobo.
   * @return payoutId
  **/
  @javax.annotation.Nonnull
  public String getPayoutId() {
    return payoutId;
  }

  public void setPayoutId(String payoutId) {
    this.payoutId = payoutId;
  }


  public PaymentPayoutItemDetail tokenId(String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

   /**
   * The token id of the payout.
   * @return tokenId
  **/
  @javax.annotation.Nullable
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  public PaymentPayoutItemDetail chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

   /**
   * The ID of the blockchain network on which the payout occurred.
   * @return chainId
  **/
  @javax.annotation.Nullable
  public String getChainId() {
    return chainId;
  }

  public void setChainId(String chainId) {
    this.chainId = chainId;
  }


  public PaymentPayoutItemDetail merchantId(String merchantId) {
    this.merchantId = merchantId;
    return this;
  }

   /**
   * The Merchant ID associated with this payout.
   * @return merchantId
  **/
  @javax.annotation.Nullable
  public String getMerchantId() {
    return merchantId;
  }

  public void setMerchantId(String merchantId) {
    this.merchantId = merchantId;
  }


  public PaymentPayoutItemDetail amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The payout token_id amount. 
   * @return amount
  **/
  @javax.annotation.Nonnull
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }


  public PaymentPayoutItemDetail status(PaymentPayoutStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nonnull
  public PaymentPayoutStatus getStatus() {
    return status;
  }

  public void setStatus(PaymentPayoutStatus status) {
    this.status = status;
  }


  public PaymentPayoutItemDetail transactions(List<PaymentTransaction> transactions) {
    this.transactions = transactions;
    return this;
  }

  public PaymentPayoutItemDetail addTransactionsItem(PaymentTransaction transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * An array of transactions associated with this payout request. Each transaction represents a separate blockchain operation related to the payout process.
   * @return transactions
  **/
  @javax.annotation.Nullable
  public List<PaymentTransaction> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<PaymentTransaction> transactions) {
    this.transactions = transactions;
  }


  public PaymentPayoutItemDetail createdTimestamp(Integer createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
    return this;
  }

   /**
   * The created time of the payout, represented as a UNIX timestamp in seconds.
   * @return createdTimestamp
  **/
  @javax.annotation.Nullable
  public Integer getCreatedTimestamp() {
    return createdTimestamp;
  }

  public void setCreatedTimestamp(Integer createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }


  public PaymentPayoutItemDetail updatedTimestamp(Integer updatedTimestamp) {
    this.updatedTimestamp = updatedTimestamp;
    return this;
  }

   /**
   * The updated time of the payout, represented as a UNIX timestamp in seconds.
   * @return updatedTimestamp
  **/
  @javax.annotation.Nullable
  public Integer getUpdatedTimestamp() {
    return updatedTimestamp;
  }

  public void setUpdatedTimestamp(Integer updatedTimestamp) {
    this.updatedTimestamp = updatedTimestamp;
  }


  public PaymentPayoutItemDetail cryptoAddressId(String cryptoAddressId) {
    this.cryptoAddressId = cryptoAddressId;
    return this;
  }

   /**
   * Unique identifier for the pre-approved crypto address, used to reference the address securely in requests.
   * @return cryptoAddressId
  **/
  @javax.annotation.Nullable
  public String getCryptoAddressId() {
    return cryptoAddressId;
  }

  public void setCryptoAddressId(String cryptoAddressId) {
    this.cryptoAddressId = cryptoAddressId;
  }


  public PaymentPayoutItemDetail cryptoAddress(String cryptoAddress) {
    this.cryptoAddress = cryptoAddress;
    return this;
  }

   /**
   * The actual blockchain address to which funds were transferred.
   * @return cryptoAddress
  **/
  @javax.annotation.Nullable
  public String getCryptoAddress() {
    return cryptoAddress;
  }

  public void setCryptoAddress(String cryptoAddress) {
    this.cryptoAddress = cryptoAddress;
  }


  public PaymentPayoutItemDetail commissionFee(CommissionFee commissionFee) {
    this.commissionFee = commissionFee;
    return this;
  }

   /**
   * Get commissionFee
   * @return commissionFee
  **/
  @javax.annotation.Nullable
  public CommissionFee getCommissionFee() {
    return commissionFee;
  }

  public void setCommissionFee(CommissionFee commissionFee) {
    this.commissionFee = commissionFee;
  }


  public PaymentPayoutItemDetail bridgingFee(BridgingFee bridgingFee) {
    this.bridgingFee = bridgingFee;
    return this;
  }

   /**
   * Get bridgingFee
   * @return bridgingFee
  **/
  @javax.annotation.Nullable
  public BridgingFee getBridgingFee() {
    return bridgingFee;
  }

  public void setBridgingFee(BridgingFee bridgingFee) {
    this.bridgingFee = bridgingFee;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PaymentPayoutItemDetail instance itself
   */
  public PaymentPayoutItemDetail putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentPayoutItemDetail paymentPayoutItemDetail = (PaymentPayoutItemDetail) o;
    return Objects.equals(this.payoutItemId, paymentPayoutItemDetail.payoutItemId) &&
        Objects.equals(this.payoutId, paymentPayoutItemDetail.payoutId) &&
        Objects.equals(this.tokenId, paymentPayoutItemDetail.tokenId) &&
        Objects.equals(this.chainId, paymentPayoutItemDetail.chainId) &&
        Objects.equals(this.merchantId, paymentPayoutItemDetail.merchantId) &&
        Objects.equals(this.amount, paymentPayoutItemDetail.amount) &&
        Objects.equals(this.status, paymentPayoutItemDetail.status) &&
        Objects.equals(this.transactions, paymentPayoutItemDetail.transactions) &&
        Objects.equals(this.createdTimestamp, paymentPayoutItemDetail.createdTimestamp) &&
        Objects.equals(this.updatedTimestamp, paymentPayoutItemDetail.updatedTimestamp) &&
        Objects.equals(this.cryptoAddressId, paymentPayoutItemDetail.cryptoAddressId) &&
        Objects.equals(this.cryptoAddress, paymentPayoutItemDetail.cryptoAddress) &&
        Objects.equals(this.commissionFee, paymentPayoutItemDetail.commissionFee) &&
        Objects.equals(this.bridgingFee, paymentPayoutItemDetail.bridgingFee)&&
        Objects.equals(this.additionalProperties, paymentPayoutItemDetail.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payoutItemId, payoutId, tokenId, chainId, merchantId, amount, status, transactions, createdTimestamp, updatedTimestamp, cryptoAddressId, cryptoAddress, commissionFee, bridgingFee, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentPayoutItemDetail {\n");
    sb.append("    payoutItemId: ").append(toIndentedString(payoutItemId)).append("\n");
    sb.append("    payoutId: ").append(toIndentedString(payoutId)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    updatedTimestamp: ").append(toIndentedString(updatedTimestamp)).append("\n");
    sb.append("    cryptoAddressId: ").append(toIndentedString(cryptoAddressId)).append("\n");
    sb.append("    cryptoAddress: ").append(toIndentedString(cryptoAddress)).append("\n");
    sb.append("    commissionFee: ").append(toIndentedString(commissionFee)).append("\n");
    sb.append("    bridgingFee: ").append(toIndentedString(bridgingFee)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("payout_item_id");
    openapiFields.add("payout_id");
    openapiFields.add("token_id");
    openapiFields.add("chain_id");
    openapiFields.add("merchant_id");
    openapiFields.add("amount");
    openapiFields.add("status");
    openapiFields.add("transactions");
    openapiFields.add("created_timestamp");
    openapiFields.add("updated_timestamp");
    openapiFields.add("crypto_address_id");
    openapiFields.add("crypto_address");
    openapiFields.add("commission_fee");
    openapiFields.add("bridging_fee");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("payout_item_id");
    openapiRequiredFields.add("payout_id");
    openapiRequiredFields.add("amount");
    openapiRequiredFields.add("status");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PaymentPayoutItemDetail
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PaymentPayoutItemDetail.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentPayoutItemDetail is not found in the empty JSON string", PaymentPayoutItemDetail.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PaymentPayoutItemDetail.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("payout_item_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `payout_item_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payout_item_id").toString()));
      }
      if (!jsonObj.get("payout_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `payout_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payout_id").toString()));
      }
      if ((jsonObj.get("token_id") != null && !jsonObj.get("token_id").isJsonNull()) && !jsonObj.get("token_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_id").toString()));
      }
      if ((jsonObj.get("chain_id") != null && !jsonObj.get("chain_id").isJsonNull()) && !jsonObj.get("chain_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chain_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chain_id").toString()));
      }
      if ((jsonObj.get("merchant_id") != null && !jsonObj.get("merchant_id").isJsonNull()) && !jsonObj.get("merchant_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchant_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchant_id").toString()));
      }
      if (!jsonObj.get("amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount").toString()));
      }
      // validate the required field `status`
      PaymentPayoutStatus.validateJsonElement(jsonObj.get("status"));
      if (jsonObj.get("transactions") != null && !jsonObj.get("transactions").isJsonNull()) {
        JsonArray jsonArraytransactions = jsonObj.getAsJsonArray("transactions");
        if (jsonArraytransactions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("transactions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `transactions` to be an array in the JSON string but got `%s`", jsonObj.get("transactions").toString()));
          }

          // validate the optional field `transactions` (array)
          for (int i = 0; i < jsonArraytransactions.size(); i++) {
            PaymentTransaction.validateJsonElement(jsonArraytransactions.get(i));
          };
        }
      }
      if ((jsonObj.get("crypto_address_id") != null && !jsonObj.get("crypto_address_id").isJsonNull()) && !jsonObj.get("crypto_address_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `crypto_address_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("crypto_address_id").toString()));
      }
      if ((jsonObj.get("crypto_address") != null && !jsonObj.get("crypto_address").isJsonNull()) && !jsonObj.get("crypto_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `crypto_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("crypto_address").toString()));
      }
      // validate the optional field `commission_fee`
      if (jsonObj.get("commission_fee") != null && !jsonObj.get("commission_fee").isJsonNull()) {
        CommissionFee.validateJsonElement(jsonObj.get("commission_fee"));
      }
      // validate the optional field `bridging_fee`
      if (jsonObj.get("bridging_fee") != null && !jsonObj.get("bridging_fee").isJsonNull()) {
        BridgingFee.validateJsonElement(jsonObj.get("bridging_fee"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentPayoutItemDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentPayoutItemDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentPayoutItemDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentPayoutItemDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentPayoutItemDetail>() {
           @Override
           public void write(JsonWriter out, PaymentPayoutItemDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentPayoutItemDetail read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             PaymentPayoutItemDetail instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentPayoutItemDetail given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentPayoutItemDetail
  * @throws IOException if the JSON string is invalid with respect to PaymentPayoutItemDetail
  */
  public static PaymentPayoutItemDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentPayoutItemDetail.class);
  }

 /**
  * Convert an instance of PaymentPayoutItemDetail to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

