/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The fee type. Possible values include: - &#x60;Order&#x60;: Fees for order processing. - &#x60;Refund&#x60;: Fees for refund processing. - &#x60;CryptoSettlement&#x60;: This fee type is deprecated. Please use &#x60;CryptoPayout&#x60; instead. - &#x60;OffRampSettlement&#x60;: This fee type is deprecated. Please use &#x60;OffRampPayout&#x60; instead. - &#x60;CryptoPayout&#x60;: Fees for crypto payouts. - &#x60;CryptoPayoutBridge&#x60;: Fees for crypto payouts with cross-chain bridging. - &#x60;OffRampPayout&#x60;: Fees for fiat off-ramp payouts. 
 */
@JsonAdapter(PaymentFeeType.Adapter.class)
public enum PaymentFeeType {
  UNKNOWN(null),
  
  ORDER("Order"),
  
  REFUND("Refund"),
  
  CRYPTOSETTLEMENT("CryptoSettlement"),
  
  OFFRAMPSETTLEMENT("OffRampSettlement"),
  
  CRYPTOPAYOUT("CryptoPayout"),
  
  CRYPTOPAYOUTBRIDGE("CryptoPayoutBridge"),
  
  OFFRAMPPAYOUT("OffRampPayout");

  private String value;

  PaymentFeeType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentFeeType fromValue(String value) {
    for (PaymentFeeType b : PaymentFeeType.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PaymentFeeType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentFeeType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentFeeType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentFeeType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PaymentFeeType.fromValue(value);
  }
}

