/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.cobo.waas2.model.BankAccount;
import com.cobo.waas2.model.CommissionFee;
import com.cobo.waas2.model.PaymentPayoutItem;
import com.cobo.waas2.model.PaymentPayoutItemDetail;
import com.cobo.waas2.model.PaymentPayoutRecipientInfo;
import com.cobo.waas2.model.PaymentPayoutStatus;
import com.cobo.waas2.model.PaymentTransaction;
import com.cobo.waas2.model.PayoutChannel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * PaymentPayoutEvent
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class PaymentPayoutEvent {
  /**
   *  The data type of the event. - &#x60;Transaction&#x60;: The transaction event data. - &#x60;TSSRequest&#x60;: The TSS request event data. - &#x60;Addresses&#x60;: The addresses event data. - &#x60;WalletInfo&#x60;: The wallet information event data. - &#x60;MPCVault&#x60;: The MPC vault event data. - &#x60;Chains&#x60;: The enabled chain event data. - &#x60;Tokens&#x60;: The enabled token event data. - &#x60;TokenListing&#x60;: The token listing event data.        - &#x60;PaymentOrder&#x60;: The payment order event data. - &#x60;PaymentRefund&#x60;: The payment refund event data. - &#x60;PaymentSettlement&#x60;: The payment settlement event data. - &#x60;PaymentTransaction&#x60;: The payment transaction event data. - &#x60;PaymentAddressUpdate&#x60;: The payment address update event data. - &#x60;PaymentPayout&#x60;: The payment payout event data. - &#x60;PaymentBulkSend&#x60;: The payment bulk send event data. - &#x60;BalanceUpdateInfo&#x60;: The balance update event data. - &#x60;SuspendedToken&#x60;: The suspended token event data. - &#x60;ComplianceDisposition&#x60;: The compliance disposition event data. - &#x60;ComplianceKytScreenings&#x60;: The compliance KYT screenings event data. - &#x60;ComplianceKyaScreenings&#x60;: The compliance KYA screenings event data.
   */
  @JsonAdapter(DataTypeEnum.Adapter.class)
  public enum DataTypeEnum {
    TRANSACTION("Transaction"),
    
    TSSREQUEST("TSSRequest"),
    
    ADDRESSES("Addresses"),
    
    WALLETINFO("WalletInfo"),
    
    MPCVAULT("MPCVault"),
    
    CHAINS("Chains"),
    
    TOKENS("Tokens"),
    
    TOKENLISTING("TokenListing"),
    
    PAYMENTORDER("PaymentOrder"),
    
    PAYMENTREFUND("PaymentRefund"),
    
    PAYMENTSETTLEMENT("PaymentSettlement"),
    
    PAYMENTTRANSACTION("PaymentTransaction"),
    
    PAYMENTADDRESSUPDATE("PaymentAddressUpdate"),
    
    PAYMENTSUBSCRIPTIONUPDATE("PaymentSubscriptionUpdate"),
    
    PAYMENTCHARGEUPDATE("PaymentChargeUpdate"),
    
    PAYMENTPAYOUT("PaymentPayout"),
    
    PAYMENTBULKSEND("PaymentBulkSend"),
    
    BALANCEUPDATEINFO("BalanceUpdateInfo"),
    
    SUSPENDEDTOKEN("SuspendedToken"),
    
    COMPLIANCEDISPOSITION("ComplianceDisposition"),
    
    COMPLIANCEKYTSCREENINGS("ComplianceKytScreenings"),
    
    COMPLIANCEKYASCREENINGS("ComplianceKyaScreenings");

    private String value;

    DataTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DataTypeEnum fromValue(String value) {
      for (DataTypeEnum b : DataTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DataTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DataTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DataTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DataTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DataTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DATA_TYPE = "data_type";
  @SerializedName(SERIALIZED_NAME_DATA_TYPE)
  private DataTypeEnum dataType;

  public static final String SERIALIZED_NAME_PAYOUT_ID = "payout_id";
  @SerializedName(SERIALIZED_NAME_PAYOUT_ID)
  private String payoutId;

  public static final String SERIALIZED_NAME_REQUEST_ID = "request_id";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  private String requestId;

  public static final String SERIALIZED_NAME_PAYOUT_CHANNEL = "payout_channel";
  @SerializedName(SERIALIZED_NAME_PAYOUT_CHANNEL)
  private PayoutChannel payoutChannel;

  public static final String SERIALIZED_NAME_SOURCE_ACCOUNT = "source_account";
  @SerializedName(SERIALIZED_NAME_SOURCE_ACCOUNT)
  private String sourceAccount;

  public static final String SERIALIZED_NAME_PAYOUT_ITEMS = "payout_items";
  @SerializedName(SERIALIZED_NAME_PAYOUT_ITEMS)
  private List<PaymentPayoutItem> payoutItems = new ArrayList<>();

  public static final String SERIALIZED_NAME_RECIPIENT_INFO = "recipient_info";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_INFO)
  private PaymentPayoutRecipientInfo recipientInfo;

  public static final String SERIALIZED_NAME_INITIATOR = "initiator";
  @SerializedName(SERIALIZED_NAME_INITIATOR)
  private String initiator;

  public static final String SERIALIZED_NAME_ACTUAL_PAYOUT_AMOUNT = "actual_payout_amount";
  @SerializedName(SERIALIZED_NAME_ACTUAL_PAYOUT_AMOUNT)
  private String actualPayoutAmount;

  public static final String SERIALIZED_NAME_COMMISSION_FEES = "commission_fees";
  @SerializedName(SERIALIZED_NAME_COMMISSION_FEES)
  private List<CommissionFee> commissionFees = new ArrayList<>();

  public static final String SERIALIZED_NAME_REMARK = "remark";
  @SerializedName(SERIALIZED_NAME_REMARK)
  private String remark;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private PaymentPayoutStatus status;

  public static final String SERIALIZED_NAME_CREATED_TIMESTAMP = "created_timestamp";
  @SerializedName(SERIALIZED_NAME_CREATED_TIMESTAMP)
  private Integer createdTimestamp;

  public static final String SERIALIZED_NAME_UPDATED_TIMESTAMP = "updated_timestamp";
  @SerializedName(SERIALIZED_NAME_UPDATED_TIMESTAMP)
  private Integer updatedTimestamp;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_BANK_ACCOUNT = "bank_account";
  @SerializedName(SERIALIZED_NAME_BANK_ACCOUNT)
  private BankAccount bankAccount;

  public static final String SERIALIZED_NAME_TRANSACTIONS = "transactions";
  @SerializedName(SERIALIZED_NAME_TRANSACTIONS)
  private List<PaymentTransaction> transactions = new ArrayList<>();

  public static final String SERIALIZED_NAME_PAYOUT_ITEM_DETAILS = "payout_item_details";
  @SerializedName(SERIALIZED_NAME_PAYOUT_ITEM_DETAILS)
  private List<PaymentPayoutItemDetail> payoutItemDetails = new ArrayList<>();

  public PaymentPayoutEvent() {
  }

  public PaymentPayoutEvent dataType(DataTypeEnum dataType) {
    this.dataType = dataType;
    return this;
  }

   /**
   *  The data type of the event. - &#x60;Transaction&#x60;: The transaction event data. - &#x60;TSSRequest&#x60;: The TSS request event data. - &#x60;Addresses&#x60;: The addresses event data. - &#x60;WalletInfo&#x60;: The wallet information event data. - &#x60;MPCVault&#x60;: The MPC vault event data. - &#x60;Chains&#x60;: The enabled chain event data. - &#x60;Tokens&#x60;: The enabled token event data. - &#x60;TokenListing&#x60;: The token listing event data.        - &#x60;PaymentOrder&#x60;: The payment order event data. - &#x60;PaymentRefund&#x60;: The payment refund event data. - &#x60;PaymentSettlement&#x60;: The payment settlement event data. - &#x60;PaymentTransaction&#x60;: The payment transaction event data. - &#x60;PaymentAddressUpdate&#x60;: The payment address update event data. - &#x60;PaymentPayout&#x60;: The payment payout event data. - &#x60;PaymentBulkSend&#x60;: The payment bulk send event data. - &#x60;BalanceUpdateInfo&#x60;: The balance update event data. - &#x60;SuspendedToken&#x60;: The suspended token event data. - &#x60;ComplianceDisposition&#x60;: The compliance disposition event data. - &#x60;ComplianceKytScreenings&#x60;: The compliance KYT screenings event data. - &#x60;ComplianceKyaScreenings&#x60;: The compliance KYA screenings event data.
   * @return dataType
  **/
  @javax.annotation.Nonnull
  public DataTypeEnum getDataType() {
    return dataType;
  }

  public void setDataType(DataTypeEnum dataType) {
    this.dataType = dataType;
  }


  public PaymentPayoutEvent payoutId(String payoutId) {
    this.payoutId = payoutId;
    return this;
  }

   /**
   * The payout ID generated by Cobo.
   * @return payoutId
  **/
  @javax.annotation.Nonnull
  public String getPayoutId() {
    return payoutId;
  }

  public void setPayoutId(String payoutId) {
    this.payoutId = payoutId;
  }


  public PaymentPayoutEvent requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * The request ID provided by you when creating the payout.
   * @return requestId
  **/
  @javax.annotation.Nonnull
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }


  public PaymentPayoutEvent payoutChannel(PayoutChannel payoutChannel) {
    this.payoutChannel = payoutChannel;
    return this;
  }

   /**
   * Get payoutChannel
   * @return payoutChannel
  **/
  @javax.annotation.Nonnull
  public PayoutChannel getPayoutChannel() {
    return payoutChannel;
  }

  public void setPayoutChannel(PayoutChannel payoutChannel) {
    this.payoutChannel = payoutChannel;
  }


  public PaymentPayoutEvent sourceAccount(String sourceAccount) {
    this.sourceAccount = sourceAccount;
    return this;
  }

   /**
   * required
   * @return sourceAccount
  **/
  @javax.annotation.Nullable
  public String getSourceAccount() {
    return sourceAccount;
  }

  public void setSourceAccount(String sourceAccount) {
    this.sourceAccount = sourceAccount;
  }


  public PaymentPayoutEvent payoutItems(List<PaymentPayoutItem> payoutItems) {
    this.payoutItems = payoutItems;
    return this;
  }

  public PaymentPayoutEvent addPayoutItemsItem(PaymentPayoutItem payoutItemsItem) {
    if (this.payoutItems == null) {
      this.payoutItems = new ArrayList<>();
    }
    this.payoutItems.add(payoutItemsItem);
    return this;
  }

   /**
   * required
   * @return payoutItems
  **/
  @javax.annotation.Nullable
  public List<PaymentPayoutItem> getPayoutItems() {
    return payoutItems;
  }

  public void setPayoutItems(List<PaymentPayoutItem> payoutItems) {
    this.payoutItems = payoutItems;
  }


  public PaymentPayoutEvent recipientInfo(PaymentPayoutRecipientInfo recipientInfo) {
    this.recipientInfo = recipientInfo;
    return this;
  }

   /**
   * Get recipientInfo
   * @return recipientInfo
  **/
  @javax.annotation.Nullable
  public PaymentPayoutRecipientInfo getRecipientInfo() {
    return recipientInfo;
  }

  public void setRecipientInfo(PaymentPayoutRecipientInfo recipientInfo) {
    this.recipientInfo = recipientInfo;
  }


  public PaymentPayoutEvent initiator(String initiator) {
    this.initiator = initiator;
    return this;
  }

   /**
   * The initiator of this payout, usually the user&#39;s API key.
   * @return initiator
  **/
  @javax.annotation.Nullable
  public String getInitiator() {
    return initiator;
  }

  public void setInitiator(String initiator) {
    this.initiator = initiator;
  }


  public PaymentPayoutEvent actualPayoutAmount(String actualPayoutAmount) {
    this.actualPayoutAmount = actualPayoutAmount;
    return this;
  }

   /**
   * In crypto bridge, the actual amount of the recipient_info token in the payout. In offramp, the actual amount of the recipient_info currency in the payout. 
   * @return actualPayoutAmount
  **/
  @javax.annotation.Nullable
  public String getActualPayoutAmount() {
    return actualPayoutAmount;
  }

  public void setActualPayoutAmount(String actualPayoutAmount) {
    this.actualPayoutAmount = actualPayoutAmount;
  }


  public PaymentPayoutEvent commissionFees(List<CommissionFee> commissionFees) {
    this.commissionFees = commissionFees;
    return this;
  }

  public PaymentPayoutEvent addCommissionFeesItem(CommissionFee commissionFeesItem) {
    if (this.commissionFees == null) {
      this.commissionFees = new ArrayList<>();
    }
    this.commissionFees.add(commissionFeesItem);
    return this;
  }

   /**
   * commission fees
   * @return commissionFees
  **/
  @javax.annotation.Nullable
  public List<CommissionFee> getCommissionFees() {
    return commissionFees;
  }

  public void setCommissionFees(List<CommissionFee> commissionFees) {
    this.commissionFees = commissionFees;
  }


  public PaymentPayoutEvent remark(String remark) {
    this.remark = remark;
    return this;
  }

   /**
   * The remark for the create payouts.
   * @return remark
  **/
  @javax.annotation.Nullable
  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }


  public PaymentPayoutEvent status(PaymentPayoutStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nonnull
  public PaymentPayoutStatus getStatus() {
    return status;
  }

  public void setStatus(PaymentPayoutStatus status) {
    this.status = status;
  }


  public PaymentPayoutEvent createdTimestamp(Integer createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
    return this;
  }

   /**
   * The created time of the payout, represented as a UNIX timestamp in seconds.
   * @return createdTimestamp
  **/
  @javax.annotation.Nonnull
  public Integer getCreatedTimestamp() {
    return createdTimestamp;
  }

  public void setCreatedTimestamp(Integer createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }


  public PaymentPayoutEvent updatedTimestamp(Integer updatedTimestamp) {
    this.updatedTimestamp = updatedTimestamp;
    return this;
  }

   /**
   * The updated time of the payout, represented as a UNIX timestamp in seconds.
   * @return updatedTimestamp
  **/
  @javax.annotation.Nonnull
  public Integer getUpdatedTimestamp() {
    return updatedTimestamp;
  }

  public void setUpdatedTimestamp(Integer updatedTimestamp) {
    this.updatedTimestamp = updatedTimestamp;
  }


  public PaymentPayoutEvent currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * The fiat currency for the payout. deprecated
   * @return currency
  **/
  @javax.annotation.Nullable
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public PaymentPayoutEvent bankAccount(BankAccount bankAccount) {
    this.bankAccount = bankAccount;
    return this;
  }

   /**
   * Get bankAccount
   * @return bankAccount
  **/
  @javax.annotation.Nullable
  public BankAccount getBankAccount() {
    return bankAccount;
  }

  public void setBankAccount(BankAccount bankAccount) {
    this.bankAccount = bankAccount;
  }


  public PaymentPayoutEvent transactions(List<PaymentTransaction> transactions) {
    this.transactions = transactions;
    return this;
  }

  public PaymentPayoutEvent addTransactionsItem(PaymentTransaction transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * An array of payout transactions.
   * @return transactions
  **/
  @javax.annotation.Nullable
  public List<PaymentTransaction> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<PaymentTransaction> transactions) {
    this.transactions = transactions;
  }


  public PaymentPayoutEvent payoutItemDetails(List<PaymentPayoutItemDetail> payoutItemDetails) {
    this.payoutItemDetails = payoutItemDetails;
    return this;
  }

  public PaymentPayoutEvent addPayoutItemDetailsItem(PaymentPayoutItemDetail payoutItemDetailsItem) {
    if (this.payoutItemDetails == null) {
      this.payoutItemDetails = new ArrayList<>();
    }
    this.payoutItemDetails.add(payoutItemDetailsItem);
    return this;
  }

   /**
   * deprecated
   * @return payoutItemDetails
  **/
  @javax.annotation.Nullable
  public List<PaymentPayoutItemDetail> getPayoutItemDetails() {
    return payoutItemDetails;
  }

  public void setPayoutItemDetails(List<PaymentPayoutItemDetail> payoutItemDetails) {
    this.payoutItemDetails = payoutItemDetails;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PaymentPayoutEvent instance itself
   */
  public PaymentPayoutEvent putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentPayoutEvent paymentPayoutEvent = (PaymentPayoutEvent) o;
    return Objects.equals(this.dataType, paymentPayoutEvent.dataType) &&
        Objects.equals(this.payoutId, paymentPayoutEvent.payoutId) &&
        Objects.equals(this.requestId, paymentPayoutEvent.requestId) &&
        Objects.equals(this.payoutChannel, paymentPayoutEvent.payoutChannel) &&
        Objects.equals(this.sourceAccount, paymentPayoutEvent.sourceAccount) &&
        Objects.equals(this.payoutItems, paymentPayoutEvent.payoutItems) &&
        Objects.equals(this.recipientInfo, paymentPayoutEvent.recipientInfo) &&
        Objects.equals(this.initiator, paymentPayoutEvent.initiator) &&
        Objects.equals(this.actualPayoutAmount, paymentPayoutEvent.actualPayoutAmount) &&
        Objects.equals(this.commissionFees, paymentPayoutEvent.commissionFees) &&
        Objects.equals(this.remark, paymentPayoutEvent.remark) &&
        Objects.equals(this.status, paymentPayoutEvent.status) &&
        Objects.equals(this.createdTimestamp, paymentPayoutEvent.createdTimestamp) &&
        Objects.equals(this.updatedTimestamp, paymentPayoutEvent.updatedTimestamp) &&
        Objects.equals(this.currency, paymentPayoutEvent.currency) &&
        Objects.equals(this.bankAccount, paymentPayoutEvent.bankAccount) &&
        Objects.equals(this.transactions, paymentPayoutEvent.transactions) &&
        Objects.equals(this.payoutItemDetails, paymentPayoutEvent.payoutItemDetails)&&
        Objects.equals(this.additionalProperties, paymentPayoutEvent.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataType, payoutId, requestId, payoutChannel, sourceAccount, payoutItems, recipientInfo, initiator, actualPayoutAmount, commissionFees, remark, status, createdTimestamp, updatedTimestamp, currency, bankAccount, transactions, payoutItemDetails, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentPayoutEvent {\n");
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("    payoutId: ").append(toIndentedString(payoutId)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    payoutChannel: ").append(toIndentedString(payoutChannel)).append("\n");
    sb.append("    sourceAccount: ").append(toIndentedString(sourceAccount)).append("\n");
    sb.append("    payoutItems: ").append(toIndentedString(payoutItems)).append("\n");
    sb.append("    recipientInfo: ").append(toIndentedString(recipientInfo)).append("\n");
    sb.append("    initiator: ").append(toIndentedString(initiator)).append("\n");
    sb.append("    actualPayoutAmount: ").append(toIndentedString(actualPayoutAmount)).append("\n");
    sb.append("    commissionFees: ").append(toIndentedString(commissionFees)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    updatedTimestamp: ").append(toIndentedString(updatedTimestamp)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    bankAccount: ").append(toIndentedString(bankAccount)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    payoutItemDetails: ").append(toIndentedString(payoutItemDetails)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("data_type");
    openapiFields.add("payout_id");
    openapiFields.add("request_id");
    openapiFields.add("payout_channel");
    openapiFields.add("source_account");
    openapiFields.add("payout_items");
    openapiFields.add("recipient_info");
    openapiFields.add("initiator");
    openapiFields.add("actual_payout_amount");
    openapiFields.add("commission_fees");
    openapiFields.add("remark");
    openapiFields.add("status");
    openapiFields.add("created_timestamp");
    openapiFields.add("updated_timestamp");
    openapiFields.add("currency");
    openapiFields.add("bank_account");
    openapiFields.add("transactions");
    openapiFields.add("payout_item_details");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("data_type");
    openapiRequiredFields.add("payout_id");
    openapiRequiredFields.add("request_id");
    openapiRequiredFields.add("payout_channel");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("created_timestamp");
    openapiRequiredFields.add("updated_timestamp");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PaymentPayoutEvent
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PaymentPayoutEvent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentPayoutEvent is not found in the empty JSON string", PaymentPayoutEvent.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PaymentPayoutEvent.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("data_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `data_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("data_type").toString()));
      }
      // validate the required field `data_type`
      DataTypeEnum.validateJsonElement(jsonObj.get("data_type"));
      if (!jsonObj.get("payout_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `payout_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payout_id").toString()));
      }
      if (!jsonObj.get("request_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `request_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("request_id").toString()));
      }
      // validate the required field `payout_channel`
      PayoutChannel.validateJsonElement(jsonObj.get("payout_channel"));
      if ((jsonObj.get("source_account") != null && !jsonObj.get("source_account").isJsonNull()) && !jsonObj.get("source_account").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source_account` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source_account").toString()));
      }
      if (jsonObj.get("payout_items") != null && !jsonObj.get("payout_items").isJsonNull()) {
        JsonArray jsonArraypayoutItems = jsonObj.getAsJsonArray("payout_items");
        if (jsonArraypayoutItems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("payout_items").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `payout_items` to be an array in the JSON string but got `%s`", jsonObj.get("payout_items").toString()));
          }

          // validate the optional field `payout_items` (array)
          for (int i = 0; i < jsonArraypayoutItems.size(); i++) {
            PaymentPayoutItem.validateJsonElement(jsonArraypayoutItems.get(i));
          };
        }
      }
      // validate the optional field `recipient_info`
      if (jsonObj.get("recipient_info") != null && !jsonObj.get("recipient_info").isJsonNull()) {
        PaymentPayoutRecipientInfo.validateJsonElement(jsonObj.get("recipient_info"));
      }
      if ((jsonObj.get("initiator") != null && !jsonObj.get("initiator").isJsonNull()) && !jsonObj.get("initiator").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `initiator` to be a primitive type in the JSON string but got `%s`", jsonObj.get("initiator").toString()));
      }
      if ((jsonObj.get("actual_payout_amount") != null && !jsonObj.get("actual_payout_amount").isJsonNull()) && !jsonObj.get("actual_payout_amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `actual_payout_amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("actual_payout_amount").toString()));
      }
      if (jsonObj.get("commission_fees") != null && !jsonObj.get("commission_fees").isJsonNull()) {
        JsonArray jsonArraycommissionFees = jsonObj.getAsJsonArray("commission_fees");
        if (jsonArraycommissionFees != null) {
          // ensure the json data is an array
          if (!jsonObj.get("commission_fees").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `commission_fees` to be an array in the JSON string but got `%s`", jsonObj.get("commission_fees").toString()));
          }

          // validate the optional field `commission_fees` (array)
          for (int i = 0; i < jsonArraycommissionFees.size(); i++) {
            CommissionFee.validateJsonElement(jsonArraycommissionFees.get(i));
          };
        }
      }
      if ((jsonObj.get("remark") != null && !jsonObj.get("remark").isJsonNull()) && !jsonObj.get("remark").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `remark` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remark").toString()));
      }
      // validate the required field `status`
      PaymentPayoutStatus.validateJsonElement(jsonObj.get("status"));
      if ((jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) && !jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      // validate the optional field `bank_account`
      if (jsonObj.get("bank_account") != null && !jsonObj.get("bank_account").isJsonNull()) {
        BankAccount.validateJsonElement(jsonObj.get("bank_account"));
      }
      if (jsonObj.get("transactions") != null && !jsonObj.get("transactions").isJsonNull()) {
        JsonArray jsonArraytransactions = jsonObj.getAsJsonArray("transactions");
        if (jsonArraytransactions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("transactions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `transactions` to be an array in the JSON string but got `%s`", jsonObj.get("transactions").toString()));
          }

          // validate the optional field `transactions` (array)
          for (int i = 0; i < jsonArraytransactions.size(); i++) {
            PaymentTransaction.validateJsonElement(jsonArraytransactions.get(i));
          };
        }
      }
      if (jsonObj.get("payout_item_details") != null && !jsonObj.get("payout_item_details").isJsonNull()) {
        JsonArray jsonArraypayoutItemDetails = jsonObj.getAsJsonArray("payout_item_details");
        if (jsonArraypayoutItemDetails != null) {
          // ensure the json data is an array
          if (!jsonObj.get("payout_item_details").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `payout_item_details` to be an array in the JSON string but got `%s`", jsonObj.get("payout_item_details").toString()));
          }

          // validate the optional field `payout_item_details` (array)
          for (int i = 0; i < jsonArraypayoutItemDetails.size(); i++) {
            PaymentPayoutItemDetail.validateJsonElement(jsonArraypayoutItemDetails.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentPayoutEvent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentPayoutEvent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentPayoutEvent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentPayoutEvent.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentPayoutEvent>() {
           @Override
           public void write(JsonWriter out, PaymentPayoutEvent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentPayoutEvent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             PaymentPayoutEvent instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentPayoutEvent given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentPayoutEvent
  * @throws IOException if the JSON string is invalid with respect to PaymentPayoutEvent
  */
  public static PaymentPayoutEvent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentPayoutEvent.class);
  }

 /**
  * Convert an instance of PaymentPayoutEvent to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

