/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.cobo.waas2.model.PaymentPayoutItem;
import com.cobo.waas2.model.PaymentPayoutRecipientInfo;
import com.cobo.waas2.model.PaymentPayoutStatus;
import com.cobo.waas2.model.PaymentTransaction;
import com.cobo.waas2.model.PayoutChannel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * PaymentPayoutDetail
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class PaymentPayoutDetail {
  public static final String SERIALIZED_NAME_PAYOUT_ID = "payout_id";
  @SerializedName(SERIALIZED_NAME_PAYOUT_ID)
  private String payoutId;

  public static final String SERIALIZED_NAME_REQUEST_ID = "request_id";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  private String requestId;

  public static final String SERIALIZED_NAME_PAYOUT_CHANNEL = "payout_channel";
  @SerializedName(SERIALIZED_NAME_PAYOUT_CHANNEL)
  private PayoutChannel payoutChannel;

  public static final String SERIALIZED_NAME_SOURCE_ACCOUNT = "source_account";
  @SerializedName(SERIALIZED_NAME_SOURCE_ACCOUNT)
  private String sourceAccount;

  public static final String SERIALIZED_NAME_PAYOUT_ITEMS = "payout_items";
  @SerializedName(SERIALIZED_NAME_PAYOUT_ITEMS)
  private List<PaymentPayoutItem> payoutItems = new ArrayList<>();

  public static final String SERIALIZED_NAME_RECIPIENT_INFO = "recipient_info";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_INFO)
  private PaymentPayoutRecipientInfo recipientInfo;

  public static final String SERIALIZED_NAME_INITIATOR = "initiator";
  @SerializedName(SERIALIZED_NAME_INITIATOR)
  private String initiator;

  public static final String SERIALIZED_NAME_ACTUAL_PAYOUT_AMOUNT = "actual_payout_amount";
  @SerializedName(SERIALIZED_NAME_ACTUAL_PAYOUT_AMOUNT)
  private String actualPayoutAmount;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private PaymentPayoutStatus status;

  public static final String SERIALIZED_NAME_REMARK = "remark";
  @SerializedName(SERIALIZED_NAME_REMARK)
  private String remark;

  public static final String SERIALIZED_NAME_CREATED_TIMESTAMP = "created_timestamp";
  @SerializedName(SERIALIZED_NAME_CREATED_TIMESTAMP)
  private Integer createdTimestamp;

  public static final String SERIALIZED_NAME_UPDATED_TIMESTAMP = "updated_timestamp";
  @SerializedName(SERIALIZED_NAME_UPDATED_TIMESTAMP)
  private Integer updatedTimestamp;

  public static final String SERIALIZED_NAME_TRANSACTIONS = "transactions";
  @SerializedName(SERIALIZED_NAME_TRANSACTIONS)
  private List<PaymentTransaction> transactions = new ArrayList<>();

  public PaymentPayoutDetail() {
  }

  public PaymentPayoutDetail payoutId(String payoutId) {
    this.payoutId = payoutId;
    return this;
  }

   /**
   * The payout ID generated by Cobo.
   * @return payoutId
  **/
  @javax.annotation.Nonnull
  public String getPayoutId() {
    return payoutId;
  }

  public void setPayoutId(String payoutId) {
    this.payoutId = payoutId;
  }


  public PaymentPayoutDetail requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * The request ID provided by you when creating the payout.
   * @return requestId
  **/
  @javax.annotation.Nonnull
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }


  public PaymentPayoutDetail payoutChannel(PayoutChannel payoutChannel) {
    this.payoutChannel = payoutChannel;
    return this;
  }

   /**
   * Get payoutChannel
   * @return payoutChannel
  **/
  @javax.annotation.Nonnull
  public PayoutChannel getPayoutChannel() {
    return payoutChannel;
  }

  public void setPayoutChannel(PayoutChannel payoutChannel) {
    this.payoutChannel = payoutChannel;
  }


  public PaymentPayoutDetail sourceAccount(String sourceAccount) {
    this.sourceAccount = sourceAccount;
    return this;
  }

   /**
   * The source account from which the payout will be made. - If the source account is a merchant account, provide the merchant&#39;s ID (e.g., \&quot;M1001\&quot;). - If the source account is the developer account, use the string &#x60;\&quot;developer\&quot;&#x60;. 
   * @return sourceAccount
  **/
  @javax.annotation.Nullable
  public String getSourceAccount() {
    return sourceAccount;
  }

  public void setSourceAccount(String sourceAccount) {
    this.sourceAccount = sourceAccount;
  }


  public PaymentPayoutDetail payoutItems(List<PaymentPayoutItem> payoutItems) {
    this.payoutItems = payoutItems;
    return this;
  }

  public PaymentPayoutDetail addPayoutItemsItem(PaymentPayoutItem payoutItemsItem) {
    if (this.payoutItems == null) {
      this.payoutItems = new ArrayList<>();
    }
    this.payoutItems.add(payoutItemsItem);
    return this;
  }

   /**
   * required
   * @return payoutItems
  **/
  @javax.annotation.Nullable
  public List<PaymentPayoutItem> getPayoutItems() {
    return payoutItems;
  }

  public void setPayoutItems(List<PaymentPayoutItem> payoutItems) {
    this.payoutItems = payoutItems;
  }


  public PaymentPayoutDetail recipientInfo(PaymentPayoutRecipientInfo recipientInfo) {
    this.recipientInfo = recipientInfo;
    return this;
  }

   /**
   * Get recipientInfo
   * @return recipientInfo
  **/
  @javax.annotation.Nullable
  public PaymentPayoutRecipientInfo getRecipientInfo() {
    return recipientInfo;
  }

  public void setRecipientInfo(PaymentPayoutRecipientInfo recipientInfo) {
    this.recipientInfo = recipientInfo;
  }


  public PaymentPayoutDetail initiator(String initiator) {
    this.initiator = initiator;
    return this;
  }

   /**
   * The initiator of this payout, usually the user&#39;s API key.
   * @return initiator
  **/
  @javax.annotation.Nullable
  public String getInitiator() {
    return initiator;
  }

  public void setInitiator(String initiator) {
    this.initiator = initiator;
  }


  public PaymentPayoutDetail actualPayoutAmount(String actualPayoutAmount) {
    this.actualPayoutAmount = actualPayoutAmount;
    return this;
  }

   /**
   * - For &#x60;Crypto&#x60; payouts: The amount of cryptocurrency sent to the recipient&#39;s address, denominated in the token specified in &#x60;recipient_info.token_id&#x60;. - For &#x60;OffRamp&#x60; payouts: The amount of fiat currency sent to the recipient&#39;s bank account, denominated in the currency specified in &#x60;recipient_info.currency&#x60;. (Note: The actual amount received may be lower due to additional bank transfer fees.) 
   * @return actualPayoutAmount
  **/
  @javax.annotation.Nullable
  public String getActualPayoutAmount() {
    return actualPayoutAmount;
  }

  public void setActualPayoutAmount(String actualPayoutAmount) {
    this.actualPayoutAmount = actualPayoutAmount;
  }


  public PaymentPayoutDetail status(PaymentPayoutStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nonnull
  public PaymentPayoutStatus getStatus() {
    return status;
  }

  public void setStatus(PaymentPayoutStatus status) {
    this.status = status;
  }


  public PaymentPayoutDetail remark(String remark) {
    this.remark = remark;
    return this;
  }

   /**
   * A note or comment about the payout.
   * @return remark
  **/
  @javax.annotation.Nullable
  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }


  public PaymentPayoutDetail createdTimestamp(Integer createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
    return this;
  }

   /**
   * The created time of the payout, represented as a UNIX timestamp in seconds.
   * @return createdTimestamp
  **/
  @javax.annotation.Nonnull
  public Integer getCreatedTimestamp() {
    return createdTimestamp;
  }

  public void setCreatedTimestamp(Integer createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }


  public PaymentPayoutDetail updatedTimestamp(Integer updatedTimestamp) {
    this.updatedTimestamp = updatedTimestamp;
    return this;
  }

   /**
   * The updated time of the payout, represented as a UNIX timestamp in seconds.
   * @return updatedTimestamp
  **/
  @javax.annotation.Nonnull
  public Integer getUpdatedTimestamp() {
    return updatedTimestamp;
  }

  public void setUpdatedTimestamp(Integer updatedTimestamp) {
    this.updatedTimestamp = updatedTimestamp;
  }


  public PaymentPayoutDetail transactions(List<PaymentTransaction> transactions) {
    this.transactions = transactions;
    return this;
  }

  public PaymentPayoutDetail addTransactionsItem(PaymentTransaction transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * An array of payout transactions.
   * @return transactions
  **/
  @javax.annotation.Nullable
  public List<PaymentTransaction> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<PaymentTransaction> transactions) {
    this.transactions = transactions;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PaymentPayoutDetail instance itself
   */
  public PaymentPayoutDetail putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentPayoutDetail paymentPayoutDetail = (PaymentPayoutDetail) o;
    return Objects.equals(this.payoutId, paymentPayoutDetail.payoutId) &&
        Objects.equals(this.requestId, paymentPayoutDetail.requestId) &&
        Objects.equals(this.payoutChannel, paymentPayoutDetail.payoutChannel) &&
        Objects.equals(this.sourceAccount, paymentPayoutDetail.sourceAccount) &&
        Objects.equals(this.payoutItems, paymentPayoutDetail.payoutItems) &&
        Objects.equals(this.recipientInfo, paymentPayoutDetail.recipientInfo) &&
        Objects.equals(this.initiator, paymentPayoutDetail.initiator) &&
        Objects.equals(this.actualPayoutAmount, paymentPayoutDetail.actualPayoutAmount) &&
        Objects.equals(this.status, paymentPayoutDetail.status) &&
        Objects.equals(this.remark, paymentPayoutDetail.remark) &&
        Objects.equals(this.createdTimestamp, paymentPayoutDetail.createdTimestamp) &&
        Objects.equals(this.updatedTimestamp, paymentPayoutDetail.updatedTimestamp) &&
        Objects.equals(this.transactions, paymentPayoutDetail.transactions)&&
        Objects.equals(this.additionalProperties, paymentPayoutDetail.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payoutId, requestId, payoutChannel, sourceAccount, payoutItems, recipientInfo, initiator, actualPayoutAmount, status, remark, createdTimestamp, updatedTimestamp, transactions, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentPayoutDetail {\n");
    sb.append("    payoutId: ").append(toIndentedString(payoutId)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    payoutChannel: ").append(toIndentedString(payoutChannel)).append("\n");
    sb.append("    sourceAccount: ").append(toIndentedString(sourceAccount)).append("\n");
    sb.append("    payoutItems: ").append(toIndentedString(payoutItems)).append("\n");
    sb.append("    recipientInfo: ").append(toIndentedString(recipientInfo)).append("\n");
    sb.append("    initiator: ").append(toIndentedString(initiator)).append("\n");
    sb.append("    actualPayoutAmount: ").append(toIndentedString(actualPayoutAmount)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    updatedTimestamp: ").append(toIndentedString(updatedTimestamp)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("payout_id");
    openapiFields.add("request_id");
    openapiFields.add("payout_channel");
    openapiFields.add("source_account");
    openapiFields.add("payout_items");
    openapiFields.add("recipient_info");
    openapiFields.add("initiator");
    openapiFields.add("actual_payout_amount");
    openapiFields.add("status");
    openapiFields.add("remark");
    openapiFields.add("created_timestamp");
    openapiFields.add("updated_timestamp");
    openapiFields.add("transactions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("payout_id");
    openapiRequiredFields.add("request_id");
    openapiRequiredFields.add("payout_channel");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("created_timestamp");
    openapiRequiredFields.add("updated_timestamp");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PaymentPayoutDetail
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PaymentPayoutDetail.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentPayoutDetail is not found in the empty JSON string", PaymentPayoutDetail.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PaymentPayoutDetail.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("payout_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `payout_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payout_id").toString()));
      }
      if (!jsonObj.get("request_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `request_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("request_id").toString()));
      }
      // validate the required field `payout_channel`
      PayoutChannel.validateJsonElement(jsonObj.get("payout_channel"));
      if ((jsonObj.get("source_account") != null && !jsonObj.get("source_account").isJsonNull()) && !jsonObj.get("source_account").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source_account` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source_account").toString()));
      }
      if (jsonObj.get("payout_items") != null && !jsonObj.get("payout_items").isJsonNull()) {
        JsonArray jsonArraypayoutItems = jsonObj.getAsJsonArray("payout_items");
        if (jsonArraypayoutItems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("payout_items").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `payout_items` to be an array in the JSON string but got `%s`", jsonObj.get("payout_items").toString()));
          }

          // validate the optional field `payout_items` (array)
          for (int i = 0; i < jsonArraypayoutItems.size(); i++) {
            PaymentPayoutItem.validateJsonElement(jsonArraypayoutItems.get(i));
          };
        }
      }
      // validate the optional field `recipient_info`
      if (jsonObj.get("recipient_info") != null && !jsonObj.get("recipient_info").isJsonNull()) {
        PaymentPayoutRecipientInfo.validateJsonElement(jsonObj.get("recipient_info"));
      }
      if ((jsonObj.get("initiator") != null && !jsonObj.get("initiator").isJsonNull()) && !jsonObj.get("initiator").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `initiator` to be a primitive type in the JSON string but got `%s`", jsonObj.get("initiator").toString()));
      }
      if ((jsonObj.get("actual_payout_amount") != null && !jsonObj.get("actual_payout_amount").isJsonNull()) && !jsonObj.get("actual_payout_amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `actual_payout_amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("actual_payout_amount").toString()));
      }
      // validate the required field `status`
      PaymentPayoutStatus.validateJsonElement(jsonObj.get("status"));
      if ((jsonObj.get("remark") != null && !jsonObj.get("remark").isJsonNull()) && !jsonObj.get("remark").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `remark` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remark").toString()));
      }
      if (jsonObj.get("transactions") != null && !jsonObj.get("transactions").isJsonNull()) {
        JsonArray jsonArraytransactions = jsonObj.getAsJsonArray("transactions");
        if (jsonArraytransactions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("transactions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `transactions` to be an array in the JSON string but got `%s`", jsonObj.get("transactions").toString()));
          }

          // validate the optional field `transactions` (array)
          for (int i = 0; i < jsonArraytransactions.size(); i++) {
            PaymentTransaction.validateJsonElement(jsonArraytransactions.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentPayoutDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentPayoutDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentPayoutDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentPayoutDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentPayoutDetail>() {
           @Override
           public void write(JsonWriter out, PaymentPayoutDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentPayoutDetail read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             PaymentPayoutDetail instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentPayoutDetail given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentPayoutDetail
  * @throws IOException if the JSON string is invalid with respect to PaymentPayoutDetail
  */
  public static PaymentPayoutDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentPayoutDetail.class);
  }

 /**
  * Convert an instance of PaymentPayoutDetail to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

