/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.cobo.waas2.model.BridgingFee;
import com.cobo.waas2.model.CommissionFee;
import com.cobo.waas2.model.OtcFee;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * PaymentEstimatedFee
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class PaymentEstimatedFee {
  public static final String SERIALIZED_NAME_TOKEN_ID = "token_id";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  private String tokenId;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private String amount;

  public static final String SERIALIZED_NAME_COMMISSION_FEE = "commission_fee";
  @SerializedName(SERIALIZED_NAME_COMMISSION_FEE)
  private CommissionFee commissionFee;

  public static final String SERIALIZED_NAME_BRIDGING_FEE = "bridging_fee";
  @SerializedName(SERIALIZED_NAME_BRIDGING_FEE)
  private BridgingFee bridgingFee;

  public static final String SERIALIZED_NAME_OTC_FEE = "otc_fee";
  @SerializedName(SERIALIZED_NAME_OTC_FEE)
  private OtcFee otcFee;

  public PaymentEstimatedFee() {
  }

  public PaymentEstimatedFee tokenId(String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

   /**
   * The ID of the cryptocurrency you want to payment.
   * @return tokenId
  **/
  @javax.annotation.Nonnull
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  public PaymentEstimatedFee amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The payment amount. 
   * @return amount
  **/
  @javax.annotation.Nonnull
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }


  public PaymentEstimatedFee commissionFee(CommissionFee commissionFee) {
    this.commissionFee = commissionFee;
    return this;
  }

   /**
   * Get commissionFee
   * @return commissionFee
  **/
  @javax.annotation.Nullable
  public CommissionFee getCommissionFee() {
    return commissionFee;
  }

  public void setCommissionFee(CommissionFee commissionFee) {
    this.commissionFee = commissionFee;
  }


  public PaymentEstimatedFee bridgingFee(BridgingFee bridgingFee) {
    this.bridgingFee = bridgingFee;
    return this;
  }

   /**
   * Get bridgingFee
   * @return bridgingFee
  **/
  @javax.annotation.Nullable
  public BridgingFee getBridgingFee() {
    return bridgingFee;
  }

  public void setBridgingFee(BridgingFee bridgingFee) {
    this.bridgingFee = bridgingFee;
  }


  public PaymentEstimatedFee otcFee(OtcFee otcFee) {
    this.otcFee = otcFee;
    return this;
  }

   /**
   * Get otcFee
   * @return otcFee
  **/
  @javax.annotation.Nullable
  public OtcFee getOtcFee() {
    return otcFee;
  }

  public void setOtcFee(OtcFee otcFee) {
    this.otcFee = otcFee;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PaymentEstimatedFee instance itself
   */
  public PaymentEstimatedFee putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentEstimatedFee paymentEstimatedFee = (PaymentEstimatedFee) o;
    return Objects.equals(this.tokenId, paymentEstimatedFee.tokenId) &&
        Objects.equals(this.amount, paymentEstimatedFee.amount) &&
        Objects.equals(this.commissionFee, paymentEstimatedFee.commissionFee) &&
        Objects.equals(this.bridgingFee, paymentEstimatedFee.bridgingFee) &&
        Objects.equals(this.otcFee, paymentEstimatedFee.otcFee)&&
        Objects.equals(this.additionalProperties, paymentEstimatedFee.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tokenId, amount, commissionFee, bridgingFee, otcFee, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentEstimatedFee {\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    commissionFee: ").append(toIndentedString(commissionFee)).append("\n");
    sb.append("    bridgingFee: ").append(toIndentedString(bridgingFee)).append("\n");
    sb.append("    otcFee: ").append(toIndentedString(otcFee)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("token_id");
    openapiFields.add("amount");
    openapiFields.add("commission_fee");
    openapiFields.add("bridging_fee");
    openapiFields.add("otc_fee");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("token_id");
    openapiRequiredFields.add("amount");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PaymentEstimatedFee
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PaymentEstimatedFee.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentEstimatedFee is not found in the empty JSON string", PaymentEstimatedFee.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PaymentEstimatedFee.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("token_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_id").toString()));
      }
      if (!jsonObj.get("amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount").toString()));
      }
      // validate the optional field `commission_fee`
      if (jsonObj.get("commission_fee") != null && !jsonObj.get("commission_fee").isJsonNull()) {
        CommissionFee.validateJsonElement(jsonObj.get("commission_fee"));
      }
      // validate the optional field `bridging_fee`
      if (jsonObj.get("bridging_fee") != null && !jsonObj.get("bridging_fee").isJsonNull()) {
        BridgingFee.validateJsonElement(jsonObj.get("bridging_fee"));
      }
      // validate the optional field `otc_fee`
      if (jsonObj.get("otc_fee") != null && !jsonObj.get("otc_fee").isJsonNull()) {
        OtcFee.validateJsonElement(jsonObj.get("otc_fee"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentEstimatedFee.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentEstimatedFee' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentEstimatedFee> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentEstimatedFee.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentEstimatedFee>() {
           @Override
           public void write(JsonWriter out, PaymentEstimatedFee value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentEstimatedFee read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             PaymentEstimatedFee instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentEstimatedFee given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentEstimatedFee
  * @throws IOException if the JSON string is invalid with respect to PaymentEstimatedFee
  */
  public static PaymentEstimatedFee fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentEstimatedFee.class);
  }

 /**
  * Convert an instance of PaymentEstimatedFee to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

