/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * SwapLimitsAndLiquidity
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class SwapLimitsAndLiquidity {
  public static final String SERIALIZED_NAME_MIN_PAY_AMOUNT = "min_pay_amount";
  @SerializedName(SERIALIZED_NAME_MIN_PAY_AMOUNT)
  private String minPayAmount;

  public static final String SERIALIZED_NAME_MAX_PAY_AMOUNT = "max_pay_amount";
  @SerializedName(SERIALIZED_NAME_MAX_PAY_AMOUNT)
  private String maxPayAmount;

  public static final String SERIALIZED_NAME_MIN_GET_AMOUNT = "min_get_amount";
  @SerializedName(SERIALIZED_NAME_MIN_GET_AMOUNT)
  private String minGetAmount;

  public static final String SERIALIZED_NAME_MAX_GET_AMOUNT = "max_get_amount";
  @SerializedName(SERIALIZED_NAME_MAX_GET_AMOUNT)
  private String maxGetAmount;

  public static final String SERIALIZED_NAME_AVAILABLE_LIQUIDITY_PAY_TOKEN = "available_liquidity_pay_token";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_LIQUIDITY_PAY_TOKEN)
  private String availableLiquidityPayToken;

  public static final String SERIALIZED_NAME_AVAILABLE_LIQUIDITY_USD = "available_liquidity_usd";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_LIQUIDITY_USD)
  private String availableLiquidityUsd;

  public SwapLimitsAndLiquidity() {
  }

  public SwapLimitsAndLiquidity minPayAmount(String minPayAmount) {
    this.minPayAmount = minPayAmount;
    return this;
  }

   /**
   * The minimum amount of pay token that can be swapped.
   * @return minPayAmount
  **/
  @javax.annotation.Nullable
  public String getMinPayAmount() {
    return minPayAmount;
  }

  public void setMinPayAmount(String minPayAmount) {
    this.minPayAmount = minPayAmount;
  }


  public SwapLimitsAndLiquidity maxPayAmount(String maxPayAmount) {
    this.maxPayAmount = maxPayAmount;
    return this;
  }

   /**
   * The maximum amount of pay token that can be swapped.
   * @return maxPayAmount
  **/
  @javax.annotation.Nullable
  public String getMaxPayAmount() {
    return maxPayAmount;
  }

  public void setMaxPayAmount(String maxPayAmount) {
    this.maxPayAmount = maxPayAmount;
  }


  public SwapLimitsAndLiquidity minGetAmount(String minGetAmount) {
    this.minGetAmount = minGetAmount;
    return this;
  }

   /**
   * The minimum amount of receive token that can be swapped.
   * @return minGetAmount
  **/
  @javax.annotation.Nullable
  public String getMinGetAmount() {
    return minGetAmount;
  }

  public void setMinGetAmount(String minGetAmount) {
    this.minGetAmount = minGetAmount;
  }


  public SwapLimitsAndLiquidity maxGetAmount(String maxGetAmount) {
    this.maxGetAmount = maxGetAmount;
    return this;
  }

   /**
   * The maximum amount of receive token that can be swapped.
   * @return maxGetAmount
  **/
  @javax.annotation.Nullable
  public String getMaxGetAmount() {
    return maxGetAmount;
  }

  public void setMaxGetAmount(String maxGetAmount) {
    this.maxGetAmount = maxGetAmount;
  }


  public SwapLimitsAndLiquidity availableLiquidityPayToken(String availableLiquidityPayToken) {
    this.availableLiquidityPayToken = availableLiquidityPayToken;
    return this;
  }

   /**
   * The available liquidity denominated in pay token.
   * @return availableLiquidityPayToken
  **/
  @javax.annotation.Nullable
  public String getAvailableLiquidityPayToken() {
    return availableLiquidityPayToken;
  }

  public void setAvailableLiquidityPayToken(String availableLiquidityPayToken) {
    this.availableLiquidityPayToken = availableLiquidityPayToken;
  }


  public SwapLimitsAndLiquidity availableLiquidityUsd(String availableLiquidityUsd) {
    this.availableLiquidityUsd = availableLiquidityUsd;
    return this;
  }

   /**
   * The available liquidity denominated in USD.
   * @return availableLiquidityUsd
  **/
  @javax.annotation.Nullable
  public String getAvailableLiquidityUsd() {
    return availableLiquidityUsd;
  }

  public void setAvailableLiquidityUsd(String availableLiquidityUsd) {
    this.availableLiquidityUsd = availableLiquidityUsd;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SwapLimitsAndLiquidity instance itself
   */
  public SwapLimitsAndLiquidity putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SwapLimitsAndLiquidity swapLimitsAndLiquidity = (SwapLimitsAndLiquidity) o;
    return Objects.equals(this.minPayAmount, swapLimitsAndLiquidity.minPayAmount) &&
        Objects.equals(this.maxPayAmount, swapLimitsAndLiquidity.maxPayAmount) &&
        Objects.equals(this.minGetAmount, swapLimitsAndLiquidity.minGetAmount) &&
        Objects.equals(this.maxGetAmount, swapLimitsAndLiquidity.maxGetAmount) &&
        Objects.equals(this.availableLiquidityPayToken, swapLimitsAndLiquidity.availableLiquidityPayToken) &&
        Objects.equals(this.availableLiquidityUsd, swapLimitsAndLiquidity.availableLiquidityUsd)&&
        Objects.equals(this.additionalProperties, swapLimitsAndLiquidity.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minPayAmount, maxPayAmount, minGetAmount, maxGetAmount, availableLiquidityPayToken, availableLiquidityUsd, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SwapLimitsAndLiquidity {\n");
    sb.append("    minPayAmount: ").append(toIndentedString(minPayAmount)).append("\n");
    sb.append("    maxPayAmount: ").append(toIndentedString(maxPayAmount)).append("\n");
    sb.append("    minGetAmount: ").append(toIndentedString(minGetAmount)).append("\n");
    sb.append("    maxGetAmount: ").append(toIndentedString(maxGetAmount)).append("\n");
    sb.append("    availableLiquidityPayToken: ").append(toIndentedString(availableLiquidityPayToken)).append("\n");
    sb.append("    availableLiquidityUsd: ").append(toIndentedString(availableLiquidityUsd)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("min_pay_amount");
    openapiFields.add("max_pay_amount");
    openapiFields.add("min_get_amount");
    openapiFields.add("max_get_amount");
    openapiFields.add("available_liquidity_pay_token");
    openapiFields.add("available_liquidity_usd");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SwapLimitsAndLiquidity
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SwapLimitsAndLiquidity.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SwapLimitsAndLiquidity is not found in the empty JSON string", SwapLimitsAndLiquidity.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("min_pay_amount") != null && !jsonObj.get("min_pay_amount").isJsonNull()) && !jsonObj.get("min_pay_amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `min_pay_amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("min_pay_amount").toString()));
      }
      if ((jsonObj.get("max_pay_amount") != null && !jsonObj.get("max_pay_amount").isJsonNull()) && !jsonObj.get("max_pay_amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `max_pay_amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("max_pay_amount").toString()));
      }
      if ((jsonObj.get("min_get_amount") != null && !jsonObj.get("min_get_amount").isJsonNull()) && !jsonObj.get("min_get_amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `min_get_amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("min_get_amount").toString()));
      }
      if ((jsonObj.get("max_get_amount") != null && !jsonObj.get("max_get_amount").isJsonNull()) && !jsonObj.get("max_get_amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `max_get_amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("max_get_amount").toString()));
      }
      if ((jsonObj.get("available_liquidity_pay_token") != null && !jsonObj.get("available_liquidity_pay_token").isJsonNull()) && !jsonObj.get("available_liquidity_pay_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `available_liquidity_pay_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("available_liquidity_pay_token").toString()));
      }
      if ((jsonObj.get("available_liquidity_usd") != null && !jsonObj.get("available_liquidity_usd").isJsonNull()) && !jsonObj.get("available_liquidity_usd").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `available_liquidity_usd` to be a primitive type in the JSON string but got `%s`", jsonObj.get("available_liquidity_usd").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SwapLimitsAndLiquidity.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SwapLimitsAndLiquidity' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SwapLimitsAndLiquidity> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SwapLimitsAndLiquidity.class));

       return (TypeAdapter<T>) new TypeAdapter<SwapLimitsAndLiquidity>() {
           @Override
           public void write(JsonWriter out, SwapLimitsAndLiquidity value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SwapLimitsAndLiquidity read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             SwapLimitsAndLiquidity instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SwapLimitsAndLiquidity given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SwapLimitsAndLiquidity
  * @throws IOException if the JSON string is invalid with respect to SwapLimitsAndLiquidity
  */
  public static SwapLimitsAndLiquidity fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SwapLimitsAndLiquidity.class);
  }

 /**
  * Convert an instance of SwapLimitsAndLiquidity to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

