/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.cobo.waas2.model.TSSCurve;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * TSSKeyReshareRequest
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class TSSKeyReshareRequest {
  public static final String SERIALIZED_NAME_OLD_GROUP_ID = "old_group_id";
  @SerializedName(SERIALIZED_NAME_OLD_GROUP_ID)
  private String oldGroupId;

  public static final String SERIALIZED_NAME_ROOT_PUB_KEY = "root_pub_key";
  @SerializedName(SERIALIZED_NAME_ROOT_PUB_KEY)
  private String rootPubKey;

  public static final String SERIALIZED_NAME_CURVE = "curve";
  @SerializedName(SERIALIZED_NAME_CURVE)
  private TSSCurve curve;

  public static final String SERIALIZED_NAME_USED_NODE_IDS = "used_node_ids";
  @SerializedName(SERIALIZED_NAME_USED_NODE_IDS)
  private List<String> usedNodeIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_OLD_THRESHOLD = "old_threshold";
  @SerializedName(SERIALIZED_NAME_OLD_THRESHOLD)
  private Integer oldThreshold;

  public static final String SERIALIZED_NAME_NEW_THRESHOLD = "new_threshold";
  @SerializedName(SERIALIZED_NAME_NEW_THRESHOLD)
  private Integer newThreshold;

  public static final String SERIALIZED_NAME_NEW_NODE_IDS = "new_node_ids";
  @SerializedName(SERIALIZED_NAME_NEW_NODE_IDS)
  private List<String> newNodeIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_TASK_ID = "task_id";
  @SerializedName(SERIALIZED_NAME_TASK_ID)
  private String taskId;

  public static final String SERIALIZED_NAME_BIZ_TASK_ID = "biz_task_id";
  @SerializedName(SERIALIZED_NAME_BIZ_TASK_ID)
  private String bizTaskId;

  public TSSKeyReshareRequest() {
  }

  public TSSKeyReshareRequest oldGroupId(String oldGroupId) {
    this.oldGroupId = oldGroupId;
    return this;
  }

   /**
   * The old TSS key share group ID.
   * @return oldGroupId
  **/
  @javax.annotation.Nullable
  public String getOldGroupId() {
    return oldGroupId;
  }

  public void setOldGroupId(String oldGroupId) {
    this.oldGroupId = oldGroupId;
  }


  public TSSKeyReshareRequest rootPubKey(String rootPubKey) {
    this.rootPubKey = rootPubKey;
    return this;
  }

   /**
   * The The old TSS key share group&#39;s root extended public key.
   * @return rootPubKey
  **/
  @javax.annotation.Nullable
  public String getRootPubKey() {
    return rootPubKey;
  }

  public void setRootPubKey(String rootPubKey) {
    this.rootPubKey = rootPubKey;
  }


  public TSSKeyReshareRequest curve(TSSCurve curve) {
    this.curve = curve;
    return this;
  }

   /**
   * Get curve
   * @return curve
  **/
  @javax.annotation.Nullable
  public TSSCurve getCurve() {
    return curve;
  }

  public void setCurve(TSSCurve curve) {
    this.curve = curve;
  }


  public TSSKeyReshareRequest usedNodeIds(List<String> usedNodeIds) {
    this.usedNodeIds = usedNodeIds;
    return this;
  }

  public TSSKeyReshareRequest addUsedNodeIdsItem(String usedNodeIdsItem) {
    if (this.usedNodeIds == null) {
      this.usedNodeIds = new ArrayList<>();
    }
    this.usedNodeIds.add(usedNodeIdsItem);
    return this;
  }

   /**
   * Get usedNodeIds
   * @return usedNodeIds
  **/
  @javax.annotation.Nullable
  public List<String> getUsedNodeIds() {
    return usedNodeIds;
  }

  public void setUsedNodeIds(List<String> usedNodeIds) {
    this.usedNodeIds = usedNodeIds;
  }


  public TSSKeyReshareRequest oldThreshold(Integer oldThreshold) {
    this.oldThreshold = oldThreshold;
    return this;
  }

   /**
   * The number of key share holders required to approve each operation in the old TSS key share group.
   * @return oldThreshold
  **/
  @javax.annotation.Nullable
  public Integer getOldThreshold() {
    return oldThreshold;
  }

  public void setOldThreshold(Integer oldThreshold) {
    this.oldThreshold = oldThreshold;
  }


  public TSSKeyReshareRequest newThreshold(Integer newThreshold) {
    this.newThreshold = newThreshold;
    return this;
  }

   /**
   * The number of key share holders required to approve each operation in the new TSS key share group.
   * @return newThreshold
  **/
  @javax.annotation.Nullable
  public Integer getNewThreshold() {
    return newThreshold;
  }

  public void setNewThreshold(Integer newThreshold) {
    this.newThreshold = newThreshold;
  }


  public TSSKeyReshareRequest newNodeIds(List<String> newNodeIds) {
    this.newNodeIds = newNodeIds;
    return this;
  }

  public TSSKeyReshareRequest addNewNodeIdsItem(String newNodeIdsItem) {
    if (this.newNodeIds == null) {
      this.newNodeIds = new ArrayList<>();
    }
    this.newNodeIds.add(newNodeIdsItem);
    return this;
  }

   /**
   * Get newNodeIds
   * @return newNodeIds
  **/
  @javax.annotation.Nullable
  public List<String> getNewNodeIds() {
    return newNodeIds;
  }

  public void setNewNodeIds(List<String> newNodeIds) {
    this.newNodeIds = newNodeIds;
  }


  public TSSKeyReshareRequest taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * The task ID.
   * @return taskId
  **/
  @javax.annotation.Nullable
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }


  public TSSKeyReshareRequest bizTaskId(String bizTaskId) {
    this.bizTaskId = bizTaskId;
    return this;
  }

   /**
   * The business task ID. This field contains the TSS request ID.
   * @return bizTaskId
  **/
  @javax.annotation.Nullable
  public String getBizTaskId() {
    return bizTaskId;
  }

  public void setBizTaskId(String bizTaskId) {
    this.bizTaskId = bizTaskId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TSSKeyReshareRequest instance itself
   */
  public TSSKeyReshareRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TSSKeyReshareRequest tsSKeyReshareRequest = (TSSKeyReshareRequest) o;
    return Objects.equals(this.oldGroupId, tsSKeyReshareRequest.oldGroupId) &&
        Objects.equals(this.rootPubKey, tsSKeyReshareRequest.rootPubKey) &&
        Objects.equals(this.curve, tsSKeyReshareRequest.curve) &&
        Objects.equals(this.usedNodeIds, tsSKeyReshareRequest.usedNodeIds) &&
        Objects.equals(this.oldThreshold, tsSKeyReshareRequest.oldThreshold) &&
        Objects.equals(this.newThreshold, tsSKeyReshareRequest.newThreshold) &&
        Objects.equals(this.newNodeIds, tsSKeyReshareRequest.newNodeIds) &&
        Objects.equals(this.taskId, tsSKeyReshareRequest.taskId) &&
        Objects.equals(this.bizTaskId, tsSKeyReshareRequest.bizTaskId)&&
        Objects.equals(this.additionalProperties, tsSKeyReshareRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oldGroupId, rootPubKey, curve, usedNodeIds, oldThreshold, newThreshold, newNodeIds, taskId, bizTaskId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TSSKeyReshareRequest {\n");
    sb.append("    oldGroupId: ").append(toIndentedString(oldGroupId)).append("\n");
    sb.append("    rootPubKey: ").append(toIndentedString(rootPubKey)).append("\n");
    sb.append("    curve: ").append(toIndentedString(curve)).append("\n");
    sb.append("    usedNodeIds: ").append(toIndentedString(usedNodeIds)).append("\n");
    sb.append("    oldThreshold: ").append(toIndentedString(oldThreshold)).append("\n");
    sb.append("    newThreshold: ").append(toIndentedString(newThreshold)).append("\n");
    sb.append("    newNodeIds: ").append(toIndentedString(newNodeIds)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    bizTaskId: ").append(toIndentedString(bizTaskId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("old_group_id");
    openapiFields.add("root_pub_key");
    openapiFields.add("curve");
    openapiFields.add("used_node_ids");
    openapiFields.add("old_threshold");
    openapiFields.add("new_threshold");
    openapiFields.add("new_node_ids");
    openapiFields.add("task_id");
    openapiFields.add("biz_task_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TSSKeyReshareRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TSSKeyReshareRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TSSKeyReshareRequest is not found in the empty JSON string", TSSKeyReshareRequest.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("old_group_id") != null && !jsonObj.get("old_group_id").isJsonNull()) && !jsonObj.get("old_group_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `old_group_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("old_group_id").toString()));
      }
      if ((jsonObj.get("root_pub_key") != null && !jsonObj.get("root_pub_key").isJsonNull()) && !jsonObj.get("root_pub_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `root_pub_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("root_pub_key").toString()));
      }
      // validate the optional field `curve`
      if (jsonObj.get("curve") != null && !jsonObj.get("curve").isJsonNull()) {
        TSSCurve.validateJsonElement(jsonObj.get("curve"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("used_node_ids") != null && !jsonObj.get("used_node_ids").isJsonNull() && !jsonObj.get("used_node_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `used_node_ids` to be an array in the JSON string but got `%s`", jsonObj.get("used_node_ids").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("new_node_ids") != null && !jsonObj.get("new_node_ids").isJsonNull() && !jsonObj.get("new_node_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `new_node_ids` to be an array in the JSON string but got `%s`", jsonObj.get("new_node_ids").toString()));
      }
      if ((jsonObj.get("task_id") != null && !jsonObj.get("task_id").isJsonNull()) && !jsonObj.get("task_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `task_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("task_id").toString()));
      }
      if ((jsonObj.get("biz_task_id") != null && !jsonObj.get("biz_task_id").isJsonNull()) && !jsonObj.get("biz_task_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `biz_task_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("biz_task_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TSSKeyReshareRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TSSKeyReshareRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TSSKeyReshareRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TSSKeyReshareRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<TSSKeyReshareRequest>() {
           @Override
           public void write(JsonWriter out, TSSKeyReshareRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TSSKeyReshareRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             TSSKeyReshareRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TSSKeyReshareRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TSSKeyReshareRequest
  * @throws IOException if the JSON string is invalid with respect to TSSKeyReshareRequest
  */
  public static TSSKeyReshareRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TSSKeyReshareRequest.class);
  }

 /**
  * Convert an instance of TSSKeyReshareRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

