/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.BankProvider;
import com.cobo.waas2.model.BankSgbKyc;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BankKyc
 */
public class BankKycTest {
    private final BankKyc model = new BankKyc();

    /**
     * Model tests for BankKyc
     */
    @Test
    public void testBankKyc() {
        // TODO: test BankKyc
    }

    /**
     * Test the property 'bankProvider'
     */
    @Test
    public void bankProviderTest() {
        // TODO: test bankProvider
    }

    /**
     * Test the property 'clientType'
     */
    @Test
    public void clientTypeTest() {
        // TODO: test clientType
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'nationality'
     */
    @Test
    public void nationalityTest() {
        // TODO: test nationality
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'idType'
     */
    @Test
    public void idTypeTest() {
        // TODO: test idType
    }

    /**
     * Test the property 'idNumber'
     */
    @Test
    public void idNumberTest() {
        // TODO: test idNumber
    }

    /**
     * Test the property 'corporateType'
     */
    @Test
    public void corporateTypeTest() {
        // TODO: test corporateType
    }

}
