/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.BankPayoutBeneficiary;
import com.cobo.waas2.model.BankPayoutSender;
import com.cobo.waas2.model.BankPayoutStatus;
import com.cobo.waas2.model.BankPayoutType;
import com.cobo.waas2.model.BankProvider;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BankPayout
 */
public class BankPayoutTest {
    private final BankPayout model = new BankPayout();

    /**
     * Model tests for BankPayout
     */
    @Test
    public void testBankPayout() {
        // TODO: test BankPayout
    }

    /**
     * Test the property 'payoutId'
     */
    @Test
    public void payoutIdTest() {
        // TODO: test payoutId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'bankProvider'
     */
    @Test
    public void bankProviderTest() {
        // TODO: test bankProvider
    }

    /**
     * Test the property 'transactionCurrency'
     */
    @Test
    public void transactionCurrencyTest() {
        // TODO: test transactionCurrency
    }

    /**
     * Test the property 'transactionAmount'
     */
    @Test
    public void transactionAmountTest() {
        // TODO: test transactionAmount
    }

    /**
     * Test the property 'feeCurrency'
     */
    @Test
    public void feeCurrencyTest() {
        // TODO: test feeCurrency
    }

    /**
     * Test the property 'feeAmount'
     */
    @Test
    public void feeAmountTest() {
        // TODO: test feeAmount
    }

    /**
     * Test the property 'remarks'
     */
    @Test
    public void remarksTest() {
        // TODO: test remarks
    }

    /**
     * Test the property 'payoutType'
     */
    @Test
    public void payoutTypeTest() {
        // TODO: test payoutType
    }

    /**
     * Test the property 'sender'
     */
    @Test
    public void senderTest() {
        // TODO: test sender
    }

    /**
     * Test the property 'beneficiary'
     */
    @Test
    public void beneficiaryTest() {
        // TODO: test beneficiary
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'updatedTimestamp'
     */
    @Test
    public void updatedTimestampTest() {
        // TODO: test updatedTimestamp
    }

}
