/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IntermediaryBankInfo
 */
public class IntermediaryBankInfoTest {
    private final IntermediaryBankInfo model = new IntermediaryBankInfo();

    /**
     * Model tests for IntermediaryBankInfo
     */
    @Test
    public void testIntermediaryBankInfo() {
        // TODO: test IntermediaryBankInfo
    }

    /**
     * Test the property 'bankName'
     */
    @Test
    public void bankNameTest() {
        // TODO: test bankName
    }

    /**
     * Test the property 'bankAddress'
     */
    @Test
    public void bankAddressTest() {
        // TODO: test bankAddress
    }

    /**
     * Test the property 'bankSwiftCode'
     */
    @Test
    public void bankSwiftCodeTest() {
        // TODO: test bankSwiftCode
    }

}
