/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.PaymentSubscriptionPeriodType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentCreateSubscriptionPlan
 */
public class PaymentCreateSubscriptionPlanTest {
    private final PaymentCreateSubscriptionPlan model = new PaymentCreateSubscriptionPlan();

    /**
     * Model tests for PaymentCreateSubscriptionPlan
     */
    @Test
    public void testPaymentCreateSubscriptionPlan() {
        // TODO: test PaymentCreateSubscriptionPlan
    }

    /**
     * Test the property 'developerPlanId'
     */
    @Test
    public void developerPlanIdTest() {
        // TODO: test developerPlanId
    }

    /**
     * Test the property 'periodType'
     */
    @Test
    public void periodTypeTest() {
        // TODO: test periodType
    }

    /**
     * Test the property 'periods'
     */
    @Test
    public void periodsTest() {
        // TODO: test periods
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'trialPeriod'
     */
    @Test
    public void trialPeriodTest() {
        // TODO: test trialPeriod
    }

}
