/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.TokenizationERC20FundTokenParams;
import com.cobo.waas2.model.TokenizationERC20FundTokenPermissionParams;
import com.cobo.waas2.model.TokenizationERC20TokenParams;
import com.cobo.waas2.model.TokenizationERC20WrappedTokenParams;
import com.cobo.waas2.model.TokenizationSOLTokenExtensions;
import com.cobo.waas2.model.TokenizationSOLTokenParams;
import com.cobo.waas2.model.TokenizationSOLWrappedTokenParams;
import com.cobo.waas2.model.TokenizationTokenStandard;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TokenizationIssueTokenParamsTokenParams
 */
public class TokenizationIssueTokenParamsTokenParamsTest {
    private final TokenizationIssueTokenParamsTokenParams model = new TokenizationIssueTokenParamsTokenParams();

    /**
     * Model tests for TokenizationIssueTokenParamsTokenParams
     */
    @Test
    public void testTokenizationIssueTokenParamsTokenParams() {
        // TODO: test TokenizationIssueTokenParamsTokenParams
    }

    /**
     * Test the property 'standard'
     */
    @Test
    public void standardTest() {
        // TODO: test standard
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'decimals'
     */
    @Test
    public void decimalsTest() {
        // TODO: test decimals
    }

    /**
     * Test the property 'tokenAccessActivated'
     */
    @Test
    public void tokenAccessActivatedTest() {
        // TODO: test tokenAccessActivated
    }

    /**
     * Test the property 'permissions'
     */
    @Test
    public void permissionsTest() {
        // TODO: test permissions
    }

    /**
     * Test the property 'underlyingToken'
     */
    @Test
    public void underlyingTokenTest() {
        // TODO: test underlyingToken
    }

    /**
     * Test the property 'extensions'
     */
    @Test
    public void extensionsTest() {
        // TODO: test extensions
    }

    /**
     * Test the property 'assetToken'
     */
    @Test
    public void assetTokenTest() {
        // TODO: test assetToken
    }

    /**
     * Test the property 'initialNav'
     */
    @Test
    public void initialNavTest() {
        // TODO: test initialNav
    }

    /**
     * Test the property 'initialAnnualRate'
     */
    @Test
    public void initialAnnualRateTest() {
        // TODO: test initialAnnualRate
    }

    /**
     * Test the property 'minDeposit'
     */
    @Test
    public void minDepositTest() {
        // TODO: test minDeposit
    }

    /**
     * Test the property 'minRedemption'
     */
    @Test
    public void minRedemptionTest() {
        // TODO: test minRedemption
    }

    /**
     * Test the property 'maxAnnualRate'
     */
    @Test
    public void maxAnnualRateTest() {
        // TODO: test maxAnnualRate
    }

    /**
     * Test the property 'maxRateChange'
     */
    @Test
    public void maxRateChangeTest() {
        // TODO: test maxRateChange
    }

    /**
     * Test the property 'minUpdateIntervalSeconds'
     */
    @Test
    public void minUpdateIntervalSecondsTest() {
        // TODO: test minUpdateIntervalSeconds
    }

}
