/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.TokenizationSOLTokenExtensions;
import com.cobo.waas2.model.TokenizationSolTokenPermissionParams;
import com.cobo.waas2.model.TokenizationTokenStandard;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TokenizationSOLTokenParams
 */
public class TokenizationSOLTokenParamsTest {
    private final TokenizationSOLTokenParams model = new TokenizationSOLTokenParams();

    /**
     * Model tests for TokenizationSOLTokenParams
     */
    @Test
    public void testTokenizationSOLTokenParams() {
        // TODO: test TokenizationSOLTokenParams
    }

    /**
     * Test the property 'standard'
     */
    @Test
    public void standardTest() {
        // TODO: test standard
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'decimals'
     */
    @Test
    public void decimalsTest() {
        // TODO: test decimals
    }

    /**
     * Test the property 'tokenAccessActivated'
     */
    @Test
    public void tokenAccessActivatedTest() {
        // TODO: test tokenAccessActivated
    }

    /**
     * Test the property 'permissions'
     */
    @Test
    public void permissionsTest() {
        // TODO: test permissions
    }

    /**
     * Test the property 'extensions'
     */
    @Test
    public void extensionsTest() {
        // TODO: test extensions
    }

}
