/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.WebhookEventType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TriggerTestPaymentsWebhookEventRequest
 */
public class TriggerTestPaymentsWebhookEventRequestTest {
    private final TriggerTestPaymentsWebhookEventRequest model = new TriggerTestPaymentsWebhookEventRequest();

    /**
     * Model tests for TriggerTestPaymentsWebhookEventRequest
     */
    @Test
    public void testTriggerTestPaymentsWebhookEventRequest() {
        // TODO: test TriggerTestPaymentsWebhookEventRequest
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'overrideData'
     */
    @Test
    public void overrideDataTest() {
        // TODO: test overrideData
    }

}
